### ISSUE TITLE
JDK 10 https "triplestore resource" configuration to remote host issue

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis#103]
The Exception thrown is this:
```
HttpException: -1 Unexpected error making the query: java.net.NoRouteToHostException: No route to host (Host unreachable)
```
with the trellis configuration:
```
resources: https://fuseki:8443/fuseki/trellis
```

using the identical configuration in the JDK 8 build works.  I suspect that it is yet another JDK 10 SSL Context or X509 hostname verification issue.  There might be a way to configure and/or inject a custom HttpClient used by RDFConnection?

This is probably directly a Jena issue.  I would like to have an option that would allow a more configurable remote triplestore resource client for Trellis.  I understand that RDFConnection is convenient, but I personally do not like having to depend on the Apache Client for everything in the triplestore resource service.

**Comment by acoburn** [comment]
Is the cert for `fuseki` self-signed? And if so, when you list the certs in the JDK keystore (`$JAVA_HOME/lib/security/cacerts`) is there an entry for this self-signed cert? Likewise, if the cert has been signed by a central cert authority, is that authority listed in the `cacerts` store?

**Comment by acoburn** [comment]
This issue seems to be specific to a JDK 10 environment, using a non-FQDN. I am going to close this issue as out-of-scope for Trellis.
