### ISSUE TITLE
TriplestoreResourceService: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis#119]
I think there is a unsynchronized collection problem in` jena.atlas.lib.SinkToCollection`.  

In the attached, you can see what happens under heavy load provided by a repeated PUT test.  
[AtlasSinkNonSynchronizedCollectionException.txt](https://github.com/trellis-ldp/trellis/files/1957453/AtlasSinkNonSynchronizedCollectionException.txt)
The method chain is:
```
org.trellisldp.triplestore.TriplestoreResourceService.storeAndNotify
org.apache.jena.arq.sparql.modify.request.QuadAccSink.addQuad
org.apache.jena.base.atlas.lib.SinkToCollection.send
```
This seems to be an upstream issue, so this is just for tracking that.

**Comment by christopher-johnson** [comment]
https://issues.apache.org/jira/browse/JENA-1536
Changing to a synchronized method seems to fix the issue.

**Comment by christopher-johnson** [comment]
Is there a downside for [Sink](https://github.com/apache/jena/blob/master/jena-base/src/main/java/org/apache/jena/atlas/lib/Sink.java) to be synchronized?  It looks this was considered in the comment, but it is not clear to me what he means by "if sync looses sync".

**Comment by christopher-johnson** [comment]
Does not biased locking help this?  I have read that in JDK 10 there is no difference for single threaded syncs. [1]  Anyway, we can probably assume that there is some performance degradation with sync, even though it may be infintesimal.  The larger question for Jena is should that method be synched or not?  I would argue that it should, since multithreaded updates are a probability.

[1] bugs.openjdk.java.net/browse/JDK-8181778

**Comment by ajs6f** [comment]
1) I know of literally no one who is deploying on JDK10 and it's not a LTR release. I can pretty well guarantee you that Jena isn't going to target behavior from non-LTS releases.

2) I don't understand how you intend to argue that this class should have a `synchronized` method, but I think you should make that argument on the Jena ticket.

3) As I noted at that ticket, there is a straightforward fix for this in the Trellis codebase.

**Comment by acoburn** [comment]
I see no reason to force a particular concurrency model on an upstream application (in this case, Jena) when it can be easily handled downstream (in this case, in the Trellis impl).

**Comment by christopher-johnson** [comment]
Ok.  Agreed.

**Comment by afs** [comment]
`QuadAccSink` supports the execution of SPARQL Update and its javadoc says: `/** Accumulate quads into a Sink (including allowing variables) during parsing. */`. Parsing is single threaded.  Concurrent use is not in the design space of `QuadAccSink`. If Trellis can get it to work, fine, but thats beyond its use in Jena.

**Comment by acoburn** [comment]
@afs thanks for the background, and yes, I think the current design of `QuadAccSink` is perfectly workable.
