### ISSUE TITLE
Add CDI support to HTTP (and other) classes

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#12]
[CDI](https://docs.oracle.com/javaee/7/tutorial/cdi-basic.htm) offers a standard J2EE-based dependency injection framework that could greatly simplify object creation in Trellis.

**Comment by ajs6f** [comment]
:+1: x 17.

**Comment by acoburn** [comment]
(Note to self) A bit part of this issue will involve removing the ability to pass `null` values into various constructors. Instead, a "null component" such as the `NoopEventService` should be used in those cases. This will allow for JSR 330 `Inject` annotations to be more easily used.

For example, the `EventService` parameter in the `TriplestoreResourceService` will need to become required instead of being wrapped in an `Optional`.
