### ISSUE TITLE
add more vocabulary terms

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis#123]
this is a low priority issue, but has one primary purpose:  to reduce the warnings in the CI build console.  Vocabulary expansion also overlaps with some things I am working on at UBL.

**Comment by acoburn** [comment]
@christopher-johnson if this issue is just about reducing the console warnings during tests, the easiest solution may be to simply change [this line](https://github.com/trellis-ldp/trellis/blob/master/core/vocabulary/src/test/java/org/trellisldp/vocabulary/AbstractVocabularyTest.java#L96) and [this line](https://github.com/trellis-ldp/trellis/blob/master/core/vocabulary/src/test/java/org/trellisldp/vocabulary/AbstractVocabularyTest.java#L79) to use `LOGGER.debug` instead of `LOGGER.warn`.

Some of these vocabularies are really large, and in those cases, I have been pretty selective about which terms to include. That said, if you have specific terms that you'd like to have included, please do send a PR with the additions.

**Comment by acoburn** [comment]
@christopher-johnson I turned down the logging on this (`warn` => `debug`). If you'd like to add new vocabulary terms, please feel free to send a PR with the new terms.

**Comment by christopher-johnson** [comment]
I worked today with the https://www.w3.org/ns/rdftest vocabulary for earl tests.  This might be a useful addition.  There are a lot of terms out there.  Regarding the selectivity in Trellis, is there a downside to including terms that could used by downstream apps?  Clearly, `trellis-vocabulary` should not be expected to fulfill all use cases.

**Comment by ajs6f** [comment]
> is there a downside to including terms that could used by downstream apps? 

More code, more maintenance. Better to offer a strong pattern for managing vocabulary that can be quickly used by downstream software.

**Comment by acoburn** [comment]
I definitely don't want `trellis-vocabulary` to be a catch-all for any conceivable RDF vocabulary out there. Thus far, I've been pretty selective with the vocabularies that are included; basically, they need to be widely used (mostly they are W3C vocabs + DC + Foaf). The other criterion is that the vocabulary gets used by the Trellis server code itself -- and mostly those vocabs are used by the core HTTP layer itself.

One thing to mention here is that the vocabulary code in Trellis is really, really simple. And while that could be an argument for adding more vocabularies to Trellis itself, there's a good argument to be made for hosting those, more specialized vocabularies in the downstream applications.

It is possibly worth noting that neither `OWL` nor `DC 1.1` are present. But if there are terms from the existing vocabs that are absent (and which should be included), or if you have a strong argument for why a certain vocab should be included, I'd definitely listen.

**Comment by acoburn** [comment]
And related specifically to the RDFTest vocabulary, Jena already has a class for this: https://jena.apache.org/documentation/javadoc/jena/org/apache/jena/vocabulary/RDFTest.html

And if your downstream application needs a Commons-RDF `IRI`, it's easy to convert an `o.a.j.vocabulary.Property` or `o.a.j.vocabulary.Resource` into an `o.a.c.rdf.api.IRI`:

```java
final JenaRDF rdf = new JenaRDF();
final IRI iri = (IRI) rdf.asRDFTerm(RDFTest.document.asNode());
```

**Comment by christopher-johnson** [comment]
In clear view of the merits of minimalism, I think that this issue can be closed.  Adding extraneous vocabulary terms for downstream consumers is out of scope with Trellis.  And, the logging issue has been resolved without having to add nonsense like `FOAF.skypeID` ...
