### ISSUE TITLE
Simplify handling of Binary objects in the API

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#126]
At present, metadata for `Binary` objects (location, size, mime-type, etc) are explicitly added to the internal `Dataset` in the `trellis:PreferServerManaged` graph. It would simplify the `ResourceService::create` and `ResourceService::replace` if one of the parameters is a (nullable) `Binary` object. Then, a persistence implementation can do whatever it needs to do with that data. It also gets the HTTP layer entirely out of the business of writing server-managed triples.

**Comment by ajs6f** [comment]
> gets the HTTP layer entirely out of the business of writing server-managed triples.

I think this is a strong good principle to which to keep for the long term.

**Comment by ajs6f** [comment]
This is the kind of thing that really makes me long for union types.
