### ISSUE TITLE
Bad IRI: <file:foo/b> warning in SPARQL

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis#128]
The fuseki log reports this:
```bash
fuseki     | [2018-05-03 07:33:58] SPARQL     WARN  [line: 32, col: 86] Bad IRI: <file:55/1a/ba/551aba6a-5e85-463b-b4a2-c4496bff018b> Code: 57/REQUIRED_COMPONENT_MISSING in AUTHORITY: A component that is required by the scheme is missing.
```

This seems to be caused by the [ViolationRules](https://github.com/apache/jena/blob/master/jena-iri/src/main/java/org/apache/jena/iri/ViolationCodes.java#L621-L645) in Jena IRI that expect a `file:` authority identifier to include 3 slashes. (e.g.  `<file:///foo/b>`).  Note however that It is just a warning, and the query still works.

**Comment by ajs6f** [comment]
Is the URI appearing in a place where it must be absolute?

**Comment by christopher-johnson** [comment]
no.  I think that binary subjects using `file:` as an authority identifier could be changed.  In `FileBinaryService`,  `URI::getSchemeSpecificPart` is used to create a file with the identifier and base path, so the `file:` part is dropped.

**Comment by acoburn** [comment]
This is used internally for representing the location of binary files (from the `trellis-file` package). Given that the location of the identifier is relative to the configured binary storage location, I had been avoiding an absolute path, but we might as well follow the specification for file URIs. Either that or create our own scheme: `trellisbinary:foo/b`, but I think just making these paths absolute (with the understanding that they are absolute to the configured base location).
