### ISSUE TITLE
Client support for NodeJS / other languages?

### ISSUE THREAD

**Issue by KrishnaPG** [trellis-ldp/trellis#1309]
This project looks interesting, but from the docs it is not clear if this is specifically built for Java consumers or can be used with any HTTP/REST API clients?

For example, would like to use this from Node.JS / Javascript clients - is it possible?

Any information on that line would be very helpful. THQ.

**Comment by acoburn** [comment]
Trellis implements the [Linked Data Platform](https://www.w3.org/TR/ldp/), so a client only needs to understand HTTP and RDF. In other words, the client can be written in JavaScript, C++, Rust, Elm or any language you want.

**Comment by KrishnaPG** [comment]
Thank you @acoburn
