### ISSUE TITLE
testPatchExistingResponse and testPatchConstraint produce empty response and test failure

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis#131]
for some inexplicable reason, these two tests (actually 8 tests in total) fail for me.  Any idea?  It is nothing related to the JDK (I assume) because it happens on master with the Gradle 1.8 VM.  The response is always empty.  It happens in Travis for the JPMS build as well.

**Comment by acoburn** [comment]
This is curious. Technically, for `testPatchExistingResponse`, the test _should_ be using a Prefer header with `ldp:PreferMinimalContainer`, but it should also work with `trellis:PreferUserManaged` (I'll update the test to use the LDP term). I've tested this manually with the current state of `master`. I also haven't seen these test failures locally or on Travis-CI.

As for `testPatchConstraint`, that test isn't checking the body at all. This is the sort of body that would be returned: `{"code":409,"message":"HTTP 409 Conflict"}`, so I'm not sure why that test would be failing. Again, I'm not seeing those failures locally or on the CI jobs that run against `master`.

**Comment by christopher-johnson** [comment]
I have understood that using `./gradlew test` works in JDK8, but when using a platform runner, they fail.  The gradle test runner initializes relatively slowly (in non-modular builds) and AFAIK evaluates the entire class by default.  So, it seems like it could be a timing or initialization question with jersey test.  What I do not understand is why just these particular tests have an issue.  Is there a precondition that the resource should exist before the patch test will succeed?

**Comment by acoburn** [comment]
I have seen quite a few transient test failures, but I've never seen these particular tests fail. The other thing is that the `trellis-http` tests are all acting on mocked resources, so there are no pre-conditions or test artifacts that would affect the outcome of the test. Can you point me to a failed Travis build?

**Comment by christopher-johnson** [comment]
https://api.travis-ci.org/v3/job/371143123/log.txt from 10 days ago.  At the end of the log, 
```
Test run finished after 30638 ms
[        27 containers found      ]
[         0 containers skipped    ]
[        27 containers started    ]
[         0 containers aborted    ]
[        27 containers successful ]
[         0 containers failed     ]
[       856 tests found           ]
[         5 tests skipped         ]
[       851 tests started         ]
[         0 tests aborted         ]
[       843 tests successful      ]
[         8 tests failed          ]
```
I disabled those two tests since then.  One way to determine if this is a test runner or test problem would be to use the `junit-platform-console` directly.  I tried today, but could not make it find anything.  It also does not seem possible to have gradle just execute a single test if it is abstract.  I have made a separate test class that contained the abstractions and the concrete configure() but had the same result.  It could be also related to parallel test execution or something with `mockito`, but that would affect more than these tests, I guess.  This one is challenging...

**Comment by acoburn** [comment]
OK, I am able to reproduce these test failures on the jpms branch under jdk10. I'll need to look a little more closely to figure out what's going on.

**Comment by christopher-johnson** [comment]
I have been able to reproduce strange `PATCH` behaviour with `trellis-client` when using dropwizard test.  The test is [here](https://github.com/trellis-ldp/trellis-client/blob/master/client/src/test/java/org/trellisldp/client/LdpClientTest.java#L867-L881).  

When i switch to using a persistent deployment fixture, it works.  When I step through the method, it seems like there is something going with the memory reference for the `Graph`.  Jena processes it as a dataset correctly, but when the update returns to `execute(create(update, base), rdf.asJenaGraph(graph));`, the graph is not updated.  This could be a question of types and the rdf commons casting override.

**Comment by christopher-johnson** [comment]
this can be resolved with this (tested locally):
```java
final org.apache.jena.core.graph.Graph g = rdf.asJenaGraph(graph);
execute(create(update, base), g);
```
it looks like the jena version of the Graph object needs to be scoped in the context of `io-jena` for it to be persisted in memory (this is just an amateur speculation...).   I have no idea why it works in JDK8.

**Comment by christopher-johnson** [comment]
I have retested this fix again (on my work system) and it has resolved the issue in the AbstractLdpResourceTests, I am sure of it.  I will submit a PR shortly.
