### ISSUE TITLE
Make RDF handling more flexible

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#132]
At present, the `http` layer has [hard-coded](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/domain/RdfMediaType.java#L49-L50) support for `text/turtle`, `application/n-triples` and `application/ld+json` for incoming RDF. `application/sparql-update` is also the only supported type for `PATCH` methods. Output serializations also include a form of `RDFa` via an HTML serializer. While this aligns with what the `io-jena` module supports, it is conceivable that a different `IOService` could support a different set of concrete serializations.

If the `IOService` had a set of methods such as (there may be some better names here):

```java
Set<RDFSyntax> supportedRdfWriters();

Set<RDFSyntax> supportedRdfReaders();

Set<RDFSyntax> supportedRdfUpdaters();
```

then the `http` layer could adapt to what the given `IOService` actually supports, which might include LD-Patch syntax or Trig or something else. This change is similar to the addition of `ResourceService::supportedInteractionModels`, allowing a particular persistence layer to decide which IxN models it supports, rather than having the `core/http` layer dictating what must be supported.

**Comment by ajs6f** [comment]
+1 to this idea. Ideally, the only specific syntaxes that would be called out in the HTTP code would be those required by the rec. Maybe not even those, if the HTTP layer assumes that all IO services can support those syntaxes.

**Comment by acoburn** [comment]
FYI -- this commit changes the method signatures in the IOService, so downstream code should be adjusted accordingly. Basically, nullable parameters are put at the end of `::read` and `::write`, and the `::update` method has a `RDFSyntax` parameter added so that alternate update syntax (e.g. LD-Patch) could at some point be used.
