### ISSUE TITLE
Potential misuse of `JsonWebToken` in 2 classes

### ISSUE THREAD

**Issue by oneturkmen** [trellis-ldp/trellis#1372]
When using a field of type `JsonWebToken`, the field should also be annotated with `@Inject`. Alternative way would be to use `Provider<JsonWebToken>` - in that case, no `@Inject` is necessary.

Relevant Code (1):
https://github.com/trellis-ldp/trellis/blob/bf3da085240c4df5a01aa9d77b64098918773510/auth/jwt/src/main/java/org/trellisldp/jwt/WebIdSecurityContext.java#L29

Relevant Code (2):
https://github.com/trellis-ldp/trellis/blob/bf3da085240c4df5a01aa9d77b64098918773510/auth/jwt/src/main/java/org/trellisldp/jwt/WebIdPrincipal.java#L30

Link about JsonWebToken usage:
- https://github.com/eclipse/microprofile-jwt-auth/issues/120#issuecomment-604555375
- https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-configuring-microprofile-json-web-token (bullet point 7)

**Comment by acoburn** [comment]
Indeed. The `JsonWebToken` object _is_ injected at https://github.com/trellis-ldp/trellis/blob/bf3da085240c4df5a01aa9d77b64098918773510/auth/jwt/src/main/java/org/trellisldp/jwt/JwtAuthFilter.java#L46-L47
