### ISSUE TITLE
ETag values should consider Prefer headers

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#139]
ETags are identifiers for specific [representations](https://tools.ietf.org/html/rfc7232#section-2.3) of a resource (as opposed to identifiers for _resources_). When the content of the representation of an `RDFSource` resource can be substantially manipulated with `Prefer` headers, the ETag value should vary in a corresponding way.

That is, the ETag for a resource should be different if a client is requesting only the containment triples or only the membership triples. At present, the ETag is the same regardless of the Prefer headers applied.

**Comment by ajs6f** [comment]
I can see the idea here, but there is [another POV](https://github.com/w3c/web-annotation/issues/327#issuecomment-236742341).

**Comment by acoburn** [comment]
I believe that this case is rather different. Here, the representations are fundamentally different -- it's not just a question of the order of triples or the difference between `turtle` and `jsonld` (where the _semantic_ meaning of the responses are the same). Here, there is a representation that consists entirely of containment triples vs. a representation of the same resource that contains everything but containment triples.

This is also has a very real-world issue that I ran into. Having written a JavaScript client that makes extensive use of Prefer headers to fetch different parts of a resource (i.e. with the intention of putting containment triples in part of the UI and user-managed triples in another part of the UI), the problem is that the first request succeeds and all subsequent requests return with a 304 Not Modified, which effectively breaks the entire JavaScript application and the whole point of being able to partition these categories of triples.

**Comment by ajs6f** [comment]
Hm. Yeah, it's different, but I don't know that either choice is good, frankly. I think this is a consequence of the fact that you can view pretty much any LDPRS as one resource with components (server-managed, not server-managed) that are managed differently, or two resources with a combined representation. I don't think there is a right answer here.
