### ISSUE TITLE
provide security configuration for remote RDFConnection

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis#141]
I am now looking at how `RDFConnection` works, as research for the future `HttpClient` question.  

I think I have discovered that Fuseki is not able to be secured from RDFConnection, since Shiro is applied in the WebContext environment.  In my test, I locked down Fuseki with a `shiro.ini ` configuration that prevents accessibility via a web request.  However, it seems that the shiro configuration is not applied at the `QueryEngineHttp` API layer, so Trellis (and presumably any Java client) can still access the data freely.  @ajs6f is this correct?  

If Fuseki would accept and process `Authorization` headers from a Java client in `RDFConnection`, then an `HttpClient` could be built in Trellis for the `RDFConnection` from a new expanded `ResourceConfiguration` that might have `BasicAuth` fields for `username` and `password` (in lieu of Fuseki being able to support JWT).

Something like this might work:
```java
if (loc.startsWith("http://") || loc.startsWith("https://")) {
      // Remote
      return create().httpClient(buildHttpClient(config)).destination(loc).build();
}

private static HttpClient buildHttpClient(final TrellisConfiguration config) {
   final Optional<String> userName = ofNullable(config.getResources().getUserName());
   final Optional<String> password = ofNullable(config.getResources().getPassword());
   final CredentialsProvider provider = new BasicCredentialsProvider();
   if (userName.isPresent() && password.isPresent()) {
       final UsernamePasswordCredentials credentials = new UsernamePasswordCredentials(
                    userName.get(), password.get());
      provider.setCredentials(AuthScope.ANY, credentials);
    }
   return HttpClientBuilder.create().setDefaultCredentialsProvider(provider).build();
 }
```

**Comment by ajs6f** [comment]
> @ajs6f is this correct?

Not correct at all. If you are using `RDFConnectionLocal` against a `Dataset` w/o HTTP involved, you have no reason to be using Fuseki and Shiro is irrelevant-- use Jena Permissions instead. If you are using a remoting `RDFConnection`, it is acting against HTTP just like any other client (the language is not relevant). If you are passing in a HTTP address for the server and going through `QueryEngineHttp` you are using a remote connection. If you aren't getting the authZ you want you probably haven't got Shiro configured as you think. Ask on users@jena.

If you want to use Shiro to guard your triplestore, use `RDFConnectionRemote` (or `RDFConnectionFuseki` for Fuseki's special features), done.

**Comment by christopher-johnson** [comment]
ok.  I figured this out.  The shiro pattern must wildcard the dataset since the API makes requests like `http://localhost:3030/fuseki/trellis?query=` so the pattern is `/**/**`.  The documentation on the different HTTP entry points to Fuseki is a bit sparse and there are no integration tests for shiro.   I was looking for a way to start a Fuseki embedded instance with a shiro.ini, which would allow an integration test for this in Trellis, but it does not seem possible.   Any suggestion?  In the meantime, I submit a PR for a BasicAuth resource configuration (without an integration test).
