### ISSUE TITLE
Add support for camel idempotent repository producer notifications

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis#145]
This is a feature request.  I am interested in the idempotent repository provided with Camel Kafka.  From what I gather, this seems to require a Camel Producer.  A Trellis Camel Producer notification module could then just depend on camel components and not messaging service directly.  The Kafka Idempotent Repository Producer would send messages to Kafka by using a context that used a registry bound to the KafkaIdempotentRepository bean.  In theory, it should be possible to make a generic Camel Producer notification module that could work with any Idempotent Repository variant.

**Comment by acoburn** [comment]
@christopher-johnson would this issue be a better fit for the [camel-ldp-recipes repository](https://github.com/trellis-ldp/camel-ldp-recipes)?

**Comment by acoburn** [comment]
Moved to https://github.com/trellis-ldp/camel-ldp-recipes/issues/5
