### ISSUE TITLE
Revisit use of Future<?> in API responses

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#148]
The current ResourceService interface responds with a `Future<>` for certain methods. A `CompletableFuture<>` could be much more flexible. Also, other *Service interfaces could benefit from using `CompletableFuture<>` responses, especially the `BinaryService`.

**Comment by ajs6f** [comment]
We could potentially replace `Optional` with `CompletableFuture` across the API in those methods which connect the backend of choice and the HTTP layer. I'm not sure whether we could do that with `Future` itself very well, tho'. Or at least we would probably go towards runtime exceptions only.

To make this kind of move, I would think we would want to select an _single_ idiom for reporting exceptional execution. With `CompletableFuture`, that would seem to be semantically-precise `Exception`s delivered in the  result itself.

Does that make sense? I really like this [`Maybe`](https://github.com/google/mug#futures) but I don't think we want to use that in the API.

**Comment by acoburn** [comment]
Yes, replacing `Optional` with a `CompletableFuture` seems like it would make a lot of sense. And 👍 to using a single idiom.

How would you suggest modeling a `ResourceService::get` request for a resource that doesn't exist (i.e. `404 Not Found`). The `Optional.empty()` response is a nice fit there, but with `CompletableFuture` are you thinking that a `null` would be returned? Or would it still return an `Optional.empty()` via `CompletableFuture<Optional<?>>`?

**Comment by ajs6f** [comment]
No, it would be a precise `Exception`, like `NoSuchResourceException` or something, that would map directly into a 404. So this
```
class NoSuchResourceException extends RuntimeException { ... }
...
CompletableFuture<Resource> notFound = new CompletableFuture<>();
notFound.completeExceptionally(new NoSuchResourceException());
return notFound;
```
kind of thing, then the caller (say, `trellis-http`) does something like
```
if (result.isCompletedExceptionally()) {
    result.exceptionally(exc -> {
        Throwable ex =  e instanceof ExecutionException || e instanceof CompletionException
                ? exc.getCause()
                : exc;
        if (ex instanceof NoSuchResourceException) {
            // rethrow and let JAX-RS map it into a 404
            throw ex;
        }
        if (ex instanceof SomeOtherReasonException) {
            // rethrow and let JAX-RS map it into something else
            throw ex;
        }
        // something else went wrong
        throw new RuntimeException(ex);
    });
} else {
    // make result into a streaming HTTP response
}
```

**Comment by ajs6f** [comment]
Hang on, that example might not work because `result` is already complete, but you get the idea.

**Comment by acoburn** [comment]
Yeah, that's clear enough.

**Comment by ajs6f** [comment]
It's also pretty gross. Maybe the "`null` object" pattern is better here, so a special `interface MIssingResource extends Resource? Then we aren't trying to write Scala so much?

**Comment by ajs6f** [comment]
```
enum SpecialResources  implements Resource { 
    MissingResource  { ... }, UnauthorizedResource { ... }, ...
}
```
?  I think I'm waxing too clever again.

**Comment by acoburn** [comment]
Let's give this a week or two to sit, giving us an opportunity to think through the implementation details. Generally, though, it seems like a good direction.

**Comment by ajs6f** [comment]
Yeah, no need to jump the gun.

**Comment by ajs6f** [comment]
On a call @acoburn noted [AsyncResponse](https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/container/AsyncResponse.html) as of interest here. We will want to meet the JAX-RS specification with as little friction as is practical.

**Comment by ajs6f** [comment]
[Java 8 EE](https://abhirockzz.wordpress.com/2017/08/07/completionstage-support-in-server-side-jax-rs/) makes this even more attractive.

**Comment by ajs6f** [comment]
The more I think about it, the more I think that the question is: does Trellis assume that it is much quicker to check for the existence of something than to retrieve that something? If not, there is an ambiguity of the `Optional<Future>` or `Future<Optional>` sort. If so, that plus the JAX-RS implications suggests to me that the answer is `Optional<CompletableFuture>` or the like. If Trellis's Java API offers that, the HTTP layer can either 404 or start responding asynchronously.

**Comment by acoburn** [comment]
`Optional<CompletableFuture>` makes sense to me, too.

**Comment by acoburn** [comment]
... or would it be better for `ResourceService::get` responses to simply be `CompletableFuture<Resource>`? In the case of a 404, the response could be a `null` value (or a runtime exception). In this case, I'm not sure how much is to be gained by wrapping the `CompletableFuture` in an `Optional`.

**Comment by christopher-johnson** [comment]
I could be mistaken, but `ResourceService::get` works as a sort of internal client?   Perhaps unrelated, but could such an internal client also work in conjunction with an HTTP/2 push promise?  Not sure how `trellis-http` could facilitate push promises, but theoretically, the HTTP request could use a `CompletableFuture<HttpResponse<?>>>` to request some container of multiple resources using something like [this](https://github.com/pan-dora/jdk11-httpclient-tests/blob/master/httpclient/src/test/java/net/httpclient/http2/ServerPush.java).  The HTTP/2 test server in the JDK11 is a decent [reference](https://github.com/pan-dora/jdk11-httpclient-tests/tree/master/httpclient/src/test/java/net/httpclient/http2/server).

**Comment by acoburn** [comment]
`ResourceService::get` is an internal client in only a certain sense. It is the interface to some persistence layer, which may or may not (but likely won't) have anything to do with HTTP. All of the HTTP abstractions are in a higher layer of the Trellis stack. A persistence layer could, in principle, implement this method with HTTP/2 push if the persistence layer involved some type of HTTP interaction, but that would be an implementation detail -- not a part of the `trellis-api` interface.

**Comment by ajs6f** [comment]
I agree that `Optional` is really... "verbose". Not the best word, but you know what I mean.

How about a null-object pattern? Return `CompletableFuture<Resource>`, and offer a singleton `class NoSuchResourceFound implements Resource`? It's not an exception, it's just... *special*.

I don't much like returning `null` inside monadish stuff. But I'm not clear that `CompletableFuture` has a _completed_ "empty" other than just completed with the value `null`. I'll take a look at that.

Or yes, an exception. I guess 404s are rare enough in fully-automated systems that they really are exceptional.

**Comment by acoburn** [comment]
I agree about `null`. With a class such as `NoSuchResourceFound`, would you imagine that the HTTP layer would just do a `if (resource instanceof NoSuchResourceFound) { ... }` check?

If we pursue this path, there may be some other opportunities to simplify the `Resource` interface, especially w/r/t the `::isDeleted` method, but that would be a separate issue.

**Comment by ajs6f** [comment]
If it's a singleton, you don't need the type, just `NO_SUCH_RESOURCE.equals(resource)`. You know, I never thought about it much before, but in some ways, `instanceof` == `equals` is actually the definition of "singleton type".

**Comment by ajs6f** [comment]
Re: `isDeleted`, are you thinking about more special `Resource` subtypes or instances?

**Comment by acoburn** [comment]
for `isDeleted`, I am thinking more about a special instance, but with the singleton pattern described above, I don't see a big reason for changing the current structure.

Basically, the `isDeleted` method is a hint to the HTTP layer to respond with `410 Gone` while providing a mechanism for generating the Memento headers pointing to earlier versions of the resource. So in this circumstance, we need a `Resource` object, but many of the methods become irrelevant (e.g. `::stream`).

**Comment by ajs6f** [comment]
Maybe we need some supertypes for `Resource`? This feels a bit like every RDF framework out there, where three years after release everyone realizes that `Graph` should have had a supertype `ImmutableGraph` sans methods for adding and removing tuples, or `Graph` should have been immutable with a `MutableGraph` subtype.

But the semantics are not obvious to me. I don't like throwing lots of `UnsupportedOperationException`s unless we have to. I'd rather have the "less-mutable" types above the "more-mutable" types. But how?

`UnlocatableResource` (404 if not a subtype) `> LocatableResource` (410 if not a subtype) `> ExtantResource` (200)? That's damn ugly.

**Comment by acoburn** [comment]
@christopher-johnson there are three possible responses (provided no unexpected failure) to `ResourceService::get`:
  * a regular resource -- this translates to an HTTP 200
  * no resource is found -- this translates to an HTTP 404
  * a resource was once here, but it has since been deleted -- this translates to an HTTP 410

The challenge (IMO) is with the third case, since we currently need some mechanism for generating the Memento-related headers for the HTTP response, so simply throwing an exception or returning some type of null-object won't work. That's where the `Resource::isDeleted` method comes it. It's not pretty, but it's effective.

One option would be to punt on Memento headers, and simply not provide them in 410 responses (the Memento spec doesn't say that we'd have to include them, though I do think they are useful). In that case, we could just return singleton objects as per @ajs6f's suggestion above for the `404` case.

Or we can return a singleton object for `410 Gone` cases, and then have the HTTP layer look up the memento headers separately. Separating the memento lookup from the `ResourceService` (i.e. `::getMementos`) would be a good idea in the sense of decoupling these services.

Another option is to use the awkward duck-typing approach that is currently in place (i.e. `Resource::isDeleted`)

**Comment by ajs6f** [comment]
> Separating the memento lookup from the ResourceService (i.e. ::getMementos) would be a good idea in the sense of decoupling these services

`VersionService`?

**Comment by acoburn** [comment]
We already have one: [MementoService](https://trellis-ldp.github.io/trellis/apidocs/org/trellisldp/api/MementoService.html)

The `ResourceService::getMementos` (in the impls I've written) just proxies to the `MementoService`. It would be a good idea to separate those.

**Comment by ajs6f** [comment]
Ah, forgot about that. Yeah, I never noticed it before, but that is definitely an inappropriate coupling.

**Comment by acoburn** [comment]
@ajs6f I'll add a ticket for splitting out the memento service from the resource service. That should simplify this issue considerably.

**Comment by acoburn** [comment]
After some thought, I really like the suggestion of an enum pattern described here: https://github.com/trellis-ldp/trellis/issues/148#issuecomment-398454230 for the case of missing/deleted resources.

**Comment by acoburn** [comment]
All the interfaces slated for this change now make use of CompletableFuture.
