### ISSUE TITLE
Remove the ResourceService::purge method

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#166]
As with #165 , this method is not used and not implemented. It can safely be removed.

**Comment by ajs6f** [comment]
Hm, this doesn't change the HTTP behavior, does it? You can still `DELETE` a 410 to leave nothing?

**Comment by acoburn** [comment]
This doesn't change the current behavior. `DELETE` to a 410 just gives you another 410 (provided that the persistence layer keeps these things around). The idea of `::purge` was to completely remove the 410, but this was never implemented. I'm not opposed to re-adding it, but it seems useless to keep it around, unused.

**Comment by ajs6f** [comment]
SI definitely has that use case, but agreed that we can reopen the idea later. I may file a ticket to keep the use case in mind.
