### ISSUE TITLE
Completely remove a 410

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#167]
For instance of Trellis that are not in the public view, there is no reason to adhere to [LDP 6.1.2](https://www.w3.org/TR/ldp/#h-ldp-webarch-uri-reuse). It should therefore be possible to `DELETE` an already-`DELETE`d resource to have its response go from 410 to 404 and the URI because re-available for assignment.

**Comment by acoburn** [comment]
As it is currently, a `DELETE`d resource can be re-assigned at the same URL. E.g. a `DELETE` followed by a `PUT` is supported (Trellis doesn't adhere to LDP 6.1.2).

One question I would have is whether the second `DELETE` would remove all of the Mementos (and any associated binaries) or just change the responses from `410` to `404`.

**Comment by ajs6f** [comment]
I actually want to be able to end up with a 404, permanently. As for Mementos-- can we offer the right headers on a 404 response?

**Comment by acoburn** [comment]
By the "right headers", do you mean that the 404 response would contain `Link` headers pointing to historical versions?

One thing to mention here is that an implementation of the ResourceService interface doesn't need to support `410 Gone` at all. It could choose to treat a `DELETE` as a full `DELETE` and immediately offer a `404 Not Found`.

**Comment by ajs6f** [comment]
Yes, it seems reasonable in some ways (Memento headers on a 404).

There's even a third possibility: wanting to turn an "outdated" resource into a redirect to a more appropriate resource!

**Comment by acoburn** [comment]
To summarize this issue, is this the expected interaction?

1. For an existing resource, a `DELETE` will cause subsequent `GET` requests to return a `410 Gone`

2. For `410 Gone` (deleted) resources, a `DELETE` will cause subsequent `GET` requests to return a `404 Not Found`.

Is the expectation that Memento resources will continue to exist beyond any `DELETE` operation (whether a single `410 Gone` or double `410 Gone` -> `404 Not Found` interaction)?

Or would the Memento resources be removed when a `410 Gone` resource is purged with a `DELETE` operation?

The current behavior is such that, once a resource is deleted, all subsequent `GET` requests return a `410 Gone` until such time that a new resource is created at that URL. Furthermore, Memento resources persist beyond all such deletions.

**Comment by ajs6f** [comment]
After further by-voice discussion about workflow, it became clear that the current behavior is suitable for most use cases, so we'll close this issue. We can reopen if/as needed with new use cases.

**Comment by syats** [comment]
I have stumbled upon this issue again.
Could you please point me to some documentation on how I can realize the following workflow:

1. Add a container with slug  X
2. Add a resourced with slug Y contained in X
3. Remove Y
4. Remove X
5. Add a container with slug  X
6. Add a resourced with slug Y contained in X

If I do a POST for step 6, I get back a 410. If I do a PUT, all I do is modify the contents of X, but can't signal that I want the new resource contained in X.

Am I doing something wrong?
Thanks for any input.

**Comment by acoburn** [comment]
I tried this set of commands on the current `master` branch for both the triplestore- and RDBMS-based persistence layers:

```
$ curl -i http://localhost:8080/ -X POST -H"Slug: X" -H"Link: <http://www.w3.org/ns/ldp#BasicContainer>; rel=\"type\""
HTTP/1.1 201 Created

$ curl -i http://localhost:8080/X -X POST -H"Slug: Y" -H"Link: <http://www.w3.org/ns/ldp#BasicContainer>; rel=\"type\""
HTTP/1.1 201 Created

$ curl -i http://localhost:8080/X/Y -XDELETE
HTTP/1.1 204 No Content

$ curl -i http://localhost:8080/X -XDELETE
HTTP/1.1 204 No Content

$ curl -i http://localhost:8080/ -X POST -H"Slug: X" -H"Link: <http://www.w3.org/ns/ldp#BasicContainer>; rel=\"type\""
HTTP/1.1 201 Created

$ curl -i http://localhost:8080/X -X POST -H"Slug: Y" -H"Link: <http://www.w3.org/ns/ldp#BasicContainer>; rel=\"type\""
HTTP/1.1 201 Created
```

Are you using the 0.7 release or the current snapshot? And are you issuing the requests in parallel?

If you are using the current snapshot, a `PUT` can be used to create resources, but if you do that (as opposed to using `POST`) the LDP containment triples will not be added. In most cases, `POST` is the better operation for resource creation.

**Comment by syats** [comment]
I am using this one: 
https://github.com/trellis-ldp/trellis/archive/trellis-0.7.3.tar.gz

Should I pull directly from Master?  or is such a tgz generated somewhere?
I am deploying via a custom Dockerfile

**Comment by acoburn** [comment]
The master branch has seen a tremendous amount of development since the start of the 0.7 release series, and given how close we are to cutting a release in the 0.8 series (we're basically waiting on the release of an upstream dependency), I'd recommend pulling directly from `master` for now.
