### ISSUE TITLE
SNAPSHOT release?

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#173]
Hey, @acoburn! After the recent changes to the `BinaryService` API, [my Travis builds are now failing](https://travis-ci.org/ajs6f/trellis-cassandra/builds/404586110) because they are running against a pre-change release in Maven. Can we get a quick SNAPSHOT release?

**Comment by acoburn** [comment]
Uploading artifacts now....

**Comment by acoburn** [comment]
The 0.8.0-SNAPSHOT artifacts are now available.

**Comment by ajs6f** [comment]
Golden!
