### ISSUE TITLE
Remove ResourceService::export method

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#179]
This method is not used in the code base, and until there is a specific use for it, it seems unnecessary to leave it in the interface.

In addition, the ResourceService::scan method is not used (outside of the export method), so unless there are good arguments for keeping it around, I’d suggest removing that, too.

**Comment by ajs6f** [comment]
:+1: to both. Scanning is the job of proper web spider software (or just `wget -r`) and backup should be accomplished via the efficient means provided by the backend in use.

**Comment by ajs6f** [comment]
Not supporting`::scan` would simplify the Cassandra schema for that backend.
