### ISSUE TITLE
YAML committment

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#193]
Are we committed to using YAML for config files? I've got no problem with it-- just want to know before working config for Trellis/Cassandra.

**Comment by acoburn** [comment]
I don't think so. YAML / JSON / JSON-LD / whatever is fine. Personally, I am not fond of XML-based configuration files, but I have no particular commitment to one format over another. As it is, the Dropwizard stuff already accepts various formats, so I'm pretty sure that JSON-based config files already are supported "out of the box". For Trellis/Cassandra, feel free to use whatever structure/format you'd like. (FWIW, the OSGi component uses simple property lists: `key=value`)

**Comment by ajs6f** [comment]
Cool. [I may go with JSON-LD, actually](https://en.wikipedia.org/wiki/Eating_your_own_dog_food).
