### ISSUE TITLE
Move EventService into HTTP layer

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#201]
Notification events are, at present, emitted from within the backend persistence layer, which means that each persistence implementation needs to implement its own logic for emitting notifications. By moving that logic into the HTTP layer, it should be possible to generalize that behavior. This change would also put the code into a good position for supporting WebSocket-based events as in #29.

Before implementing a particular solution here, it seems that the two most obvious paths for implementation would be to either:

1. Change the mutating `ResouceService` methods so that they return a `Stream<Event>` (in this way, the persistence impl keeps track of the resources that were changed -- it gets more complicated w/ direct and indirect resources), and the HTTP layer simply emits events for whatever `Event`s were returned by the `ResourceService`.
2. Don't change the `ResourceService` interface at all, and just use the existing public methods to determine which resources changed.

I have a preference for the second option, provided that such a design is not overly cumbersome to implement (the first method would be pretty trivial to implement, but it would require all persistence layers to implement their own notification logic).

**Comment by ajs6f** [comment]
Huge -1 to the first choice. That doesn't really improve the situation: backends are still duplicating the same functionality over and over. +1 to the second-- it gets the job done, but are there missing cases? I'm not sure what you mean by "it gets more complicated w/ direct and indirect resources"…

**Comment by acoburn** [comment]
The complications with direct/indirect containers is really just that it would likely involve an extra resource lookup, but under option 2, that shouldn't really be that complicated.

**Comment by acoburn** [comment]
I'll plan to implement the second option.

**Comment by ajs6f** [comment]
👍

**Comment by acoburn** [comment]
With #204, there is no longer any particular need for the `Session` parameter on the mutating `ResourceService` methods: `create`, `replace` and `delete`. @ajs6f are you using the `Session` parameter in your `ResourceService` implementation methods? Or could we simplify the interface?

**Comment by ajs6f** [comment]
Nope-- I'm not even sure what I would do with it!
