### ISSUE TITLE
Rename http.LdpResource

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#202]
The class in the HTTP layer that does most of the work of Trellis is called `LdpResource`. It may be that `TrellisHttpResource` would be a better name for that class, and changing that for 0.8 would be a good time to do that.

**Comment by ajs6f** [comment]
+1. This reminds me to ask-- why is `LdpResource` a `ContainerRequestFilter`? Seems like a plain old resource, not a filter…

**Comment by acoburn** [comment]
The class does some pre-filtering [here](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/LdpResource.java#L186-L232), basically to map certain types of input errors to HTTP error codes. It would also be possible to move that logic into its own class, though. Putting that together was more of a convenience.

**Comment by ajs6f** [comment]
Holy moly, I never noticed that. +1 to factoring that out. It's definitely surprising. When I have time later this week, I will try to make a PR for that.
