### ISSUE TITLE
Trellis Prefix

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#21]
The `TRELLIS_PREFIX` value is currently set as `trellis:`. This leads to root containers with only that value. While Jena allows this as a valid IRI, not all commons-rdf implementations do. It would be much better to start using `trellis:data` as a root container. This will likely involve removing the `TRELLIS_PREFIX` constant and adding two new constants:

`TRELLIS_SCHEME = "trellis:"`
`TRELLIS_DATA = TRELLIS_SCHEME + "data"`

**Comment by ajs6f** [comment]
"Root container" as in "outermost" LDP container?

**Comment by acoburn** [comment]
Yes, exactly.

**Comment by ajs6f** [comment]
Gotcha. Definitely good to have a bulletproof IRI there.
