### ISSUE TITLE
Initial contents?

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#210]
Should there be any contents in a completely fresh Trellis repository? I'm having trouble getting the tests in `trellis-test` to operate correctly, and I want to make sure that it's not because of some assumption they are making about initial content. I notice that some of them seem to set up containers by `POST`ing to the root of the repo, but for my setup, that's not possible because there is no container there, so a 404 will result. 

Am I making the wrong assumption? Should all Trellis repositories init with a container at the root, and if so, does Trellis take responsibility for that or must my backend?

**Comment by acoburn** [comment]
If you're using the latest SNAPSHOTs, the HTTP layer should [auto-initialize](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java#L151-L167). You can verify this by inspecting the log output and finding something like:

    LOGGER.info("Initializing root container: {}", id);

That is, the expectation is that there is an LDP-BC at the root of the repo, but that's it.

**Comment by ajs6f** [comment]
Yeah, that's what won't work in the Cassandra impl--
```
trellis.getResourceService().get(root)...
```
doesn't work because there is no resource at root, so that bit return `MISSING_RESOURCE` and that's the end of the story.  I think it would work if the HTTP layer just blindly called `ResourceService::create` instead of checking first...

**Comment by acoburn** [comment]
If the response from `.get(root)` is a `MISSING_RESOURCE`, then it _should_ be calling the `::create` method: https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java#L170-L172

**Comment by ajs6f** [comment]
Nope. No logged message and no BC created at root.

**Comment by acoburn** [comment]
From https://github.com/ajs6f/trellis-cassandra/blob/master/impl/src/main/java/edu/si/trellis/cassandra/CassandraResourceService.java#L86-L87, I'm assuming that `.get(root)` is returning _something_. Can you check to see what that is?

**Comment by ajs6f** [comment]
Oh, I'm sure it _is_ `MISSING_RESOURCE`. I'm just telling you that the logging doesn't occur and there is no container created, but I'll set up a simple test to be sure that `MISSING_RESOURCE` is indeed the return value.

**Comment by acoburn** [comment]
Maybe in the context of the test suite, the `@PostConstruct` annotation isn't being processed? We could add some debug logging in there.

**Comment by acoburn** [comment]
https://github.com/trellis-ldp/trellis/commit/2113ec59eef08809aeebeeb59ce40d66d0da24e1

A new SNAPSHOT will be available in a few minutes.

**Comment by ajs6f** [comment]
So, after some more tinkering, I can confirm that I never see the "Initializing root container" or the "Preparing to initialize Trellis" messages. OTOH, I hacked in some initialization code that builds a basic container at the root in a `@PostConstruct` in my `ResourceService` class, and that seems to have done the trick.

It makes me wonder indeed if I'm somehow missing some of your `@PostConstruct`s. Would there be any other problems you know of that that would cause, that I could check?

**Comment by ajs6f** [comment]
After discussion, it became clear that Trellis cannot take responsibility for all initialization, so we instead chose to make implementation responsibilities as clear as possible.

Closed with https://github.com/trellis-ldp/trellis/pull/247
