### ISSUE TITLE
Make tests static

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#211]
Many of the intermediate test classes that bring together test methods and state (e.g. `BasicContainmentTests`) cannot be subclassed because they are not `static` classes (e.g. `BasicContainmentTests` isn't `static` inside `AbstractApplicationLdpTests`). 

Is this by design for some reason, or can we open those up to create some granularity for those folks (like me) who like to reuse tests at various levels?

**Comment by acoburn** [comment]
We can definitely open that up -- the idea with the test suite was to make it possible to reuse portions of it at various levels, so it would make sense to me to convert them to static classes.

**Comment by acoburn** [comment]
I looked more closely at this, and there _is_ a reason that these nested classes are not static -- they need access to the [methods of the enclosing class](https://github.com/trellis-ldp/trellis/blob/master/components/test/src/main/java/org/trellisldp/test/AbstractApplicationLdpTests.java#L184-L194). So, given this structure, we won't be able to make the nested test classes static.

**Comment by acoburn** [comment]
I'm going to close this issue, as it's not possible to make the tests `static` given the current structure.

**Comment by ajs6f** [comment]
Ok, I'll file an issue for a full refactor of the tests (to open up the points for subtyping), which would be a much larger and much less urgent project. We should only do that after a careful discussion about how people might be expected to use the tests.

**Comment by acoburn** [comment]
Yes, feel free to add an issue about refactoring the tests. While I think we're getting pretty close to a stable set of interfaces in the `api` package, the `test` module is still definitely a work in progress.
