### ISSUE TITLE
Rework Memento-related interfaces

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#22]
The current `Resource` interface contains a method for retrieving mementos: `getMementos`. While this can certainly work (it works fine for the kafka-based implementation), it means that the resource subsystem is tied to the versioning subsystem, which may not necessarily be the case. At least, I can think of cases where the two could easily be separated. As such, I would like to propose removing the `Resource::getMementos` method, and adding something similar to the `ResourceService` interface.

**Comment by ajs6f** [comment]
Big time +1. This would also clarify the available choices for new impls.
