### ISSUE TITLE
Document all configuration properties

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#225]
Most components now use Tamaya for configuration. All of these configuration properties in use should be documented in the component itself (i.e. a `javadoc` statement), in the component `README.md` file, and centrally on a trellis wiki page. The configuration values should all follow a consistent pattern, and where relevant the naming convention should be normalized.

**Comment by ajs6f** [comment]
If we're going to do Javadocs for this, I think we should define a "standard format" up front. Is there a practice we can adopt? I don't know what's downstream of Tamaya, and of course, nether do they, because open source.

**Comment by acoburn** [comment]
I've been using this format for configuration keys: `trellis.<package name>.<config key>` (more or less). Often, there is a fourth element. But because this has all been implemented piece-meal, there're really no standard. Here are some examples:

https://github.com/trellis-ldp/trellis/blob/master/components/file/src/main/java/org/trellisldp/file/FileMementoService.java#L65

https://github.com/trellis-ldp/trellis/blob/master/components/namespaces/src/main/java/org/trellisldp/namespaces/NamespacesJsonContext.java#L44

I really don't care what the "standard practice" is, but I'd like there to be some consistency in the naming.

**Comment by ajs6f** [comment]
Works for me-- let's keep going in that style.

**Comment by acoburn** [comment]
There are quite a few constants defined for this purpose, and it would be a good idea for those to have a similar format, such prefixing each with `CONFIG_`.

**Comment by ajs6f** [comment]
A common prefix is good-- would you like to go for a common way to pack the module name into the constant name? I think that would be helpful.

How about `CONFIG_MODULE_NAME_*` with hypens or anything else in the module name => underscores?
