### ISSUE TITLE
Memento headers and commas

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#239]
The [Memento specification](https://tools.ietf.org/html/rfc7089) describes two optional parameters in the associated link headers: `from` and `until`. These parameters, if included, `MUST` be formatted according to [RFC 1123](https://tools.ietf.org/html/rfc1123.html). For example: `until="Wed, 20 Jan 2010 09:34:33 GMT"`

Generating this value is no problem. The problem is that many downstream libraries that parse Link headers don't expect a comma to appear inside a link, even though putting it inside a quoted parameter is legit. This is actually a pretty significant problem from a practical perspective, and I would like to suggest that the `from` and `until` parameters be removed from the memento headers by default.

I will introduce a configuration property that can be set to enable those parameters, but I would like the default for them to be turned off.

**Comment by acoburn** [comment]
That's a really good idea. I'll send a question to their dev list.

**Comment by ajs6f** [comment]
Yeah, @hvdsomp is very responsive and I guarantee you'll get some good discussion.

**Comment by acoburn** [comment]
Thank you @martinklein0815! I think you make an excellent point about retaining the additional information in the link headers. I certainly find that information valuable. I still think there is a pragmatic reason to be able to turn off those header parameters -- for example, the LDP test suite doesn't parse those Link headers properly, and that project is not exactly maintained any longer (though it is quite useful for LDP server implementations such as this project).

What I think I'll do, based on your suggestion, is to keep these Memento headers -- both the `until` and `from` parameters for TimeMap links and the `datetime` parameter for Memento links. By default, those will be present, which will keep the additional information and (hopefully) encourage HTTP clients to "do the right think" w/r/t Link header parsing. In cases where that isn't possible, however, (such as for running the LDP test suite), I will make a configuration value available to turn off this feature.

I completely agree with your assessment of Java parsers -- this is exactly where I have encountered difficulty with this sort of header parsing. I am not at all surprised that `requests` handles this correctly; I am a big fan of that library whenever I work with Python. Is your Java parsing library available on Maven central? If so, I have code where I'd be interested in using it.

Thanks again
