### ISSUE TITLE
Rename sub-package in -http module

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#241]
The HTTP module contains three packages: `org.trellisldp.http`, `org.trellisldp.http.impl` and `org.trellisldp.http.domain`. The name of the last one (`.domain`) doesn't hold much meaning, and I am not even sure why that name was used in the first place. I would like to rename that to `.http.core`, which seems like a more appropriate name.

**Comment by ajs6f** [comment]
👍 I've wondered where `domain` came from, myself.
