### ISSUE TITLE
Review class names in tests

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#243]
The testing code should contain class names that correspond to the class being tested. So, for instance, `.http.WebSubHeaderFilter` should be tested with `.http.WebSubHeaderFilterTest`. There are numerous instances where these names differ, from capitalization differences (`WebAcFilter` => `WebACFilterTest`) to completely different names (`TrellisHttpResource` => `LdpResourceTest`) to tests with the wrong name and the wrong package (`.http.core.TimemapGenerator` => `.http.impl.MementoResourceTest`). This is a ticket to review those names.

**Comment by ajs6f** [comment]
I wonder if there's some automation we can apply here. I don't know of anything specific, but I suspect we might be able to write a really hyper-complex Checkstyle rule for this. I also suspect that would be more than a bit beyond Checkstyle's real competence, however.
