### ISSUE TITLE
Jakarta dependencies

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#249]
The JEE modules that have (as of Java 9) been removed from the JDK are now managed by the Eclipse foundation, and, as part of that transition, the [group and artifact names will change](https://wiki.eclipse.org/New_Maven_Coordinates) from `javax...` to `jakarta...`.

JAX-RS appears to be one of the first releases under the new coordinates: `jakarta.ws.rs/jakarta.ws.rs-api`.

Making this change is simple, but I also want to make sure it won't disrupt downstream development efforts.

**Comment by ajs6f** [comment]
I can catch up with this. It shouldn't be a terrible burden.

**Comment by acoburn** [comment]
The package names (for imports) don't change, so it's just a matter of adjusting the `pom.xml` or `build.gradle` files.

I'll go ahead and update this in the code and push a copy to the snapshot repos.
