### ISSUE TITLE
Build failure?

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#250]
Bizarrely, after https://github.com/trellis-ldp/trellis/commit/4bb27d0fc3a63333558ff1728040ea1d96b4cb2e I now get (from `./gradlew  clean check install`):

```
> Task :trellis-osgi:test
objc[18818]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java (0x10a1334c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10c1a24e0). One of the two will be used. Which one is undefined.

org.trellisldp.osgi.OSGiTest > testBasicAuthInstallation FAILED
    org.ops4j.pax.exam.WrappedTestContainerException

org.trellisldp.osgi.OSGiTest > testOAuthAuthInstallation FAILED
    org.ops4j.pax.exam.WrappedTestContainerException

org.trellisldp.osgi.OSGiTest > testHttpInstallation FAILED
    org.ops4j.pax.exam.WrappedTestContainerException

17 tests completed, 3 failed

> Task :trellis-osgi:test FAILED
```
Thoughts?

**Comment by acoburn** [comment]
Hmm. It seems that Travis-CI gets that [same error](https://travis-ci.com/trellis-ldp/trellis/jobs/152741034) on Java8. I was testing locally on JDK11 but will try using JDK8 instead; I may need to revert that commit.

**Comment by ajs6f** [comment]
Oh, right-- that would make sense. Well, do we want to maintain a branch, or just re-add that commit once we commit to JDK11?

**Comment by acoburn** [comment]
The commit is trivial and it will be in the history, so I'd rather not start maintaining a separate branch for this.

**Comment by acoburn** [comment]
It looks like the OSGi metadata for the new artifact won't play nicely with Java 8 environments (outside of OSGi, it should be fine), but I will go ahead and revert this.

**Comment by ajs6f** [comment]
Thanks!

**Comment by acoburn** [comment]
Closing via https://github.com/trellis-ldp/trellis/commit/d610664bed060d38f150b904787b4ee38bb19c4a
