### ISSUE TITLE
Review the constructors for the various Service implementations

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#251]
Most of the `api.*Service` implementations could be modified slightly to have fully-functional no-arg constructors. As such, these services could be made usable by the `ServiceLoader`. The `io.JenaIOService` in particular should be examined, as should the `rdfa.HtmlSerializer`.

The following modules don't currently support ServiceLoader injection:

* ~~io-jena~~
* ~~rdfa~~
* ~~triplestore~~
* ~~webac~~
* ~~file~~
* amqp
* jms
* kafka

**Comment by ajs6f** [comment]
No-arg constructors are useful for almost any DI framework.
