### ISSUE TITLE
Evaluate methods in MementoService interface

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#263]
The `MementoService` contains the following methods that need to be implemented by a persistence layer:

```java
CompletableFuture<Void> put(IRI identifier, Instant time, Stream<Quad> data);
 
CompletableFuture<Void> delete(IRI identifier, Instant time);

CompletableFuture<Resource> get(IRI identifier, Instant time);

CompletableFuture<List<Instant>> list(IRI identifier);
```

This issue is a placeholder to evaluate the design of this interface. For example, would it be better for `list` to return a `Stream<Instant>` (and be renamed)? Also, the `delete` method isn't currently used anywhere in the code: should it be removed until such time that it would really be used? Or would it be useful to keep it there for now? (removing it reduces the burden of implementation somewhat)

**Comment by ajs6f** [comment]
```
CompletableFuture<Void> put(IRI identifier, Instant time, Stream<Quad> data);
 ```
to me, makes more sense as
```
CompletableFuture<Void> put(IRI identifier, Instant time, Dataset data);
```
for "parallelism" with `MutableDataService::*`. I don't see how we get much savings from offering a `Stream` here but a `Dataset` there. WDYT?

**Comment by ajs6f** [comment]
Question about the semantics: if I do two `put`s with identical first two params but different quads/data, do I expect a replacement to occur? Do we allow rewriting history like that (I have no problem whatsoever with so doing)? Or do we somehow go to a `Map<IRI,<Multimap<Instant, Resource>>` kind of thing, if you see what I mean?

**Comment by acoburn** [comment]
Given two `put` requests with identical first params, I'd expect a replacement to occur.

As for `Stream<Quad>` vs. `Dataset`, the use of `Stream` is exceedingly convenient b/c the data comes directly from `Resource::stream` and it also allows the write operation to write directly to the persistence layer w/o buffering the entire dataset in memory.

**Comment by ajs6f** [comment]
As for replacement, makes sense to me. 

But the streaming thing... if that's the argument, doesn't it follow that we should change everything in `MutableDataService::*` to use a `Stream<Quad>` as well? Otherwise, the main path is buffered but an aux path is streaming... penny-wise and pound-foolish? Or do we accept some buffering for RDF for up-and-down-the-stack convenience, as we do in the main path?

**Comment by acoburn** [comment]
The other methods are buffered because we run some consistency checks on the user-managed triples (we don't buffer containment/membership/audit triples) -- for example, we require that certain `ldp:*` properties are present for direct containers, etc. Whereas for the memento part, we stream out the _entire_ set of quads for a resource: user-managed, containment, membership, audit. Ordinarily that whole set of data isn't ever buffered in memory.

**Comment by acoburn** [comment]
And also, for `PATCH`, we have to read the user triples into a `Graph` just to perform the sparql-update. There's really no easy way to get around that.

**Comment by acoburn** [comment]
1. I have been implementing this like so: if a memento exists for exactly this time, return that; otherwise, return the latest memento for the IRI that is no later that this time. Basically, I'm trying to respond with "the state of the resource at time X". If no Memento can be found, then return `completedFuture(MISSING_RESOURCE)`
2. Order does not matter. Also, converting it to a stream is completely fine. The reason it's a `List` has to do with the fact that the HTTP layer traverses that list twice: once to generate the `Link: @rel=memento` headers and once to generate the `Link: @rel=timemap` header, but it would be no problem to collect the data into a `List` at the point that it's actually needed.

**Comment by ajs6f** [comment]
1. Okay, I'll go with that.
2. If order doesn't matter and we're going to traverse it repeatedly anyway, let's go to a `Set`, cool?

**Comment by acoburn** [comment]
A `Set` works for me.

**Comment by ajs6f** [comment]
Good, then a further question about its type param: Mementos are stored and retrieved under an `Instant`, but `list` wants to return  a `Range<Instant>` per Memento. How is that to be calculated, or is it really just `Range.is`?

**Comment by acoburn** [comment]
Ahh, that's probably why it's a `List` right now. The [file-based Memento implementation](https://github.com/trellis-ldp/trellis/blob/master/components/file/src/main/java/org/trellisldp/file/FileMementoService.java#L164-L176) collects a `Stream<Instant>` into a sorted `List<Instant>` and then generates `Range<Instant>` values for each interval. It's a little gross, but the Memento spec wants ranges for a memento covering the time range that the Memento covers. Unless, of course, we drop the range part of the Memento header, which is technically optional; in that case, we could just return a `Set<Instant>`

**Comment by acoburn** [comment]
Let me revise what I've described above. It appears that we should be able to do without the `Range` type. A simple `Set<Instant>` should suffice. There's a little bit of refactoring that will be involved, but it should be possible to avoid all of the ugliness of the code described above while retaining all of the existing features.

**Comment by acoburn** [comment]
OK, I can confirm that we can remove the `Range` type altogether here, which will simplify the `trellis-file` implementation considerably (and probably the C* impl, too). So, do you have a preference between the method returning a `Stream<Instant>` and a `Set<Instant>`? Either way is fine from my perspective, though the semantics of a `Set` are clearer that the mementos are unique.

**Comment by ajs6f** [comment]
Awesome! I'd go `Set`, precisely because of the additional semantics. I
can't see more than a thousand or two Mementos occurring in practice, can
you?

**Comment by acoburn** [comment]
In practice, I can't really see there being that many Mementos. Until there is a use case driving that situation, though, I don't see a reason to design for it. If, at some point, we need to add a mechanism for filtering the mementos, I don't actually think that would be so difficult.

Related question: what would you think of a `SortedSet`? We don't really need a total ordering for everything, but we do need the `min` and `max` values of the collection, and by using a `SortedSet` we get those values "for free", more or less. That would also mean that the code would only need a single iteration through the collection.

**Comment by ajs6f** [comment]
We need min/max? Interesting. Yeah, if we know that elements are unique, we want a `Set`, but if we do need ordering (or at least min/max) then we do want sorting, and that is best done once. I'm good with `SortedSet`.

**Comment by ajs6f** [comment]
Okay. I'm blocked by this on Mementos for `trellis-cassandra`, so if you don't get around to it, I will.

**Comment by acoburn** [comment]
I should be able to get a PR ready this afternoon.

**Comment by acoburn** [comment]
Reopening to continue the discussion about the `MementoService::put` method.

Regarding the `Dataset` vs. `Stream<Quad>` issue, it may be possible to sidestep this entire issue. The `MementoService` contains two `::put` methods: one accepts a `Resource` and the other accepts an `IRI`, `Instant` and `Stream<Quad>`. The first method has a default implementation that calls the second method, and in the HTTP layer it is that first method that gets called (the second version is never called directly).

What if, instead, we eliminated that second method and removed the default implementation of the first method. Then an implementing class would need to implement only `MementoService.put(Resource res)`. At that point, if you want a `Dataset`, your implementation generates one from `Resource.stream().collect(toDataset())` or similar. Or if the implementation uses a `Stream<Quad>` directly, that's all just implementation details.

Thoughts on this?

**Comment by ajs6f** [comment]
First reaction: if we do that, we have one path (Mementos) using `Resource` as the payload and the other (main) path using all the information in a `Resource`, except parted out into separate params, no? I started maundering on about the `Stream` vs. `Dataset` thing out of selfish motives, but now I want to try and think about the whole architecture for a moment. 

Does the framework and its backend transact in `Resource`s, naked data fields, or something else? Or is it necessarily hybrid to obtain as much efficiency as possible?

**Comment by acoburn** [comment]
There are two services that transact in `Resource` objects: `ResourceService` and `MementoService` (the other services are not relevant here). If you divide those services between _reads_ and _writes_, all the read-related methods respond with `CompletableFuture<Resource>`, so there's consistency there. Really, this is just a question of write methods.

For _write_ methods, the `ResourceService` does not accept `Resource` objects (I believe it did at one point, though) but rather makes use of [multiple](https://github.com/trellis-ldp/trellis/blob/master/core/api/src/main/java/org/trellisldp/api/ImmutableDataService.java#L41) [arguments](https://github.com/trellis-ldp/trellis/blob/master/core/api/src/main/java/org/trellisldp/api/MutableDataService.java#L43-L70). This is the so partly out of convenience but partly also because these `Resource` objects may not yet exist in the persistence layer. Either way, the data is always going to be partial since the accompanying `Dataset`s won't include containment or membership triples. Nor will they include historical audit triples.

The `MementoService::put` method, on the other hand, will accept either a `Resource` or a set of [component arguments](https://github.com/trellis-ldp/trellis/blob/master/core/api/src/main/java/org/trellisldp/api/MementoService.java#L43-L55), though the only one that's directly called in the HTTP layer is the `MementoService::put(Resource)` version. Here, the situation is a little different, since the resource hasn't been built up from an HTTP operation (plus user-supplied payload); instead, the resource is complete: it has been fetched from `ResourceService::get`, so it will contain all of the containment, membership and audit quads that wouldn't ordinarily be available from just the user's request.

So we have this hybrid model. I think the differences largely come down to how the data get used (and what data are available and when). Which is to say that the API design has largely been pragmatic in its focus. Does that suggest a particular outcome on the `Stream` vs. `Dataset` question?

The other item to mention is that I've tried (to the extent possible) not to buffer data in memory when I can avoid it. The mutating `ResourceService` methods do get an in-memory `Dataset`, but that's only going to be a subset of all the triples that comprise that `Resource`: whenever the "full" resource is fetched, it's done only with `Stream`s.

**Comment by ajs6f** [comment]
As I now understand it, a `Resource` combines as many as three things:
1. A VALJO of the metadata, including potentially a link to `Binary` content if it's a NonRDFSource.
2. For RDFSources, a supplier for computations on the graph (i.e. `::stream`).
3. The guarantee that all of the above are in the management of the server.

From that POV, the question is when and when do these things not apply.

For `ResourceService`, it's obviously just as you say: it makes no sense to write a `Resource`, but everything coming from `::get` is clearly a `Resource`.

For `MementoService`, can we say that everything coming into `::put` (let's leave `::delete` alone for a bit, for reasons we're talking about in https://github.com/trellis-ldp/trellis/issues/245) is for reals in the management of the server (which is how you make it sound above)?

If so, then not only would going to `Resource` be more ergonomic, it would actually be more precise and helpful.

**Comment by ajs6f** [comment]
Making a PR now...

**Comment by acoburn** [comment]
Closing with #276
