### ISSUE TITLE
DELETE vs. Memento

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#282]
In our [docs](https://github.com/trellis-ldp/trellis/wiki/Resource-Management#deleting-resources) I find: 
> It is also worth noting that a DELETE operation does not remove historic versions of a resource.

In fact, the `-cassandra` impl does just that (deletes historic versions) and further, it must in order to meet one of our key requirements-- that we have a  simple path to purge (truly purge) a resource. (Think [PII](https://en.wikipedia.org/wiki/Personally_identifiable_information).)

Is there a reason to make this guarantee in the docs, or can we toast it?

**Comment by acoburn** [comment]
There's no reason to make this guarantee -- it would entirely depend on the _implementation_ of the particular MementoService. So yes, please either remove that line or change it to encompass the possibility that a `DELETE` operation truly purges the content.

**Comment by ajs6f** [comment]
Cool-- I'm going to simply remove it (strategic ambiguity!).
