### ISSUE TITLE
LdpBinaryTests  and NonRDFSource descriptions

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#283]
I'm a bit confused about our handling of NonRdfSource descriptions and how they are being tested. In the [docs](https://github.com/trellis-ldp/trellis/wiki/Resource-Management#retrieving-resources) I see:

> When Non-RDF (binary) resources are added, a corresponding RDF resource is created. Link headers will lead a client to that resource. 

which jibes with my understanding of what we are about; it shouldn't be possible to make a single URI both an RDfSource and a NonRDFSource, so we link out the description (standoff description).

But to my examination, the tests in `LdpBinaryTests` (particularly `testGetBinaryDescription` and `testPatchBinaryDescription`) try to retrieve RDF directly from a NonRDFSource-- no `Link` header is used to intermediate.

This doesn't work for the current `trellis-cassandra`, although I probably could make it work, but is it right? How are those tests passing for other impls?

**Comment by acoburn** [comment]
This is an interesting issue, and I'm not entirely sure what the correct approach is. But this is all mediated by the HTTP layer, so it _should_ work the same across implementations.

That is, if you create an LDP-NR at the URL: http://www.example.com/binary and then try to fetch the resource from that URL, you will see a link header for:

```http
Link: <http://www.example.com/binary?ext=description>; rel="describedby"
```

Requesting the URL from that Link header, you get the description. That description contains these headers:

```http
Link: <http://www.example.com/binary>; rel="describes"
Link: <http://www.example.com/binary?ext=description>; rel="canonical"
Link: <http://www.example.com/binary#description>; rel="alternate"
```

Note the `rel="alternate"` -- an HTTP server will ignore a hashURI in a request path, which means that this "alternate" URL is functionally equivalent to the binary's URL when it comes to matching the resource path.

That means if you request http://www.example.com/binary using an Accept header such as `text/turtle`, you'll get the description. Technically, you can `PATCH` to that URL with `Sparql-Update`, though the `Accept-Patch` header is only returned when the description is returned.

The reason for this convolution has to do with RDF contexts: if you `PATCH` to the description with `<>`, that _should_ expand to the value of the request URL itself, but we also want the subject of the RDF to be the binary, and the only way to do that is with this sleight of hand where the request URL context is the same as the binary while also ensuring that the LDP-NR and its description are available at separate URLs. The `?ext=description` will _only_ ever respond with RDF.

As for the `LdpBinaryTests`, those are making use of this shortcut. Technically, they should do a `HEAD` request on the binary and then operate on the subsequent `rel=describedby` Link header. And it would be a good idea to modify those tests to work that way.

**Comment by ajs6f** [comment]
Okay, that makes a bit more sense, but I agree that the tests should certainly demonstrate best practice. Shall I alter this ticket or file a new one? (Also, it seems like we should add the info you supply above to the [Resource Management page](https://github.com/trellis-ldp/trellis/wiki/Resource-Management#retrieving-resources).) It seems that something else must be going on with my impl-- I'll dig in and figure that out.

**Comment by acoburn** [comment]
I will add some of this information to that wiki page, but let's leave this issue open until the tests are fixed.

**Comment by ajs6f** [comment]
👍

**Comment by ajs6f** [comment]
Wiki edited with https://github.com/trellis-ldp/trellis/wiki/Resource-Management/04f5a6c256f758fa60e7aa4f2c2f27651a40255f
