### ISSUE TITLE
Add a WebSocket-based notification system

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#29]
The SOLID specification recommends using WebSockets for notifications, and I think this would be a good way to provide an embedded message broker for Trellis.

There are a few outstanding questions to resolve w/r/t implementation. First, SOLID suggests making websocket endpoints available on each resource. This seems like a very interesting idea, as the notifications can be scoped to a particular resource or container of resources.

  1. If a websocket is initiated at resource `/foo`, should notifications from _all_ contained resources be made available (i.e. recursively?) or just those that that relate to that resource/container?
  2. If `1.` is answered in the negative, is there a resource location where _all_ notifications can be accessed?

**Comment by christopher-johnson** [comment]
This could be relevant:
https://github.com/solid/solid/issues/70

**Comment by christopher-johnson** [comment]
>    While that is certainly a very nice feature, it would change the implementation from a fairly straight-forward event notification system to a full-featured message broker. 

RIght.  I think that a message broker is necessary if persistence is a requirement.   Would it be possible to delegate "exactly once semantics" to Kafka (et. al.) and then wire a KafkaConsumer into the Websocket interface?   What library would you use for the websocket publisher?  I noticed the the JDK incubator client has some websocket features for subscribers.  Camel support is limited for websockets, AFAIK.

**Comment by christopher-johnson** [comment]
the first bit of this would be an API for user-managed topics/subscriptions?  

A basic kafka implementation process could be:
1. user creates topic and event filter for resource/resource group
2. async stream processor applies filter and produces to new topic.
3. extension (camel?) consumes topic and publishes to websocket endpoint.  (not clear to me how to parameterize topic selector from websocket endpoint request).

**Comment by acoburn** [comment]
The current thinking is to use the Java EE [Websocket](https://docs.oracle.com/javaee/7/api/javax/websocket/package-summary.html) classes and annotations along with the [Tyrus](https://tyrus-project.github.io/) reference implementation.

**Comment by acoburn** [comment]
I would like to suggest closing this issue. WebSocket-based notifications have a lot of potential benefits, but this seems outside the scope of Trellis as an LDP server. This sort of feature could be applied as an extension module in a down-stream application, but implementing it in the Trellis repository seems unnecessary.

**Comment by ajs6f** [comment]
👍 to closing. If WebSockets takes on some new importance, we can always revisit.
