### ISSUE TITLE
Wildcard types in API

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#291]
The core API has a number of methods that return a wildcard type:

```java
interface Resource {
    Stream<? extends Quad> stream();
    Stream<? extends Triple> stream(IRI graph);   
}

interface ResourceService {
    CompletableFuture<? extends Resource> get(IRI identifier);
}
```

Do we really need this level of flexibility?

**Comment by ajs6f** [comment]
I think those are sketchy (in the artistic sense, not the slang sense). We should simply bring them over to [generics](http://www.angelikalanger.com/GenericsFAQ/FAQSections/ProgrammingIdioms.html#Should%20I%20use%20wildcards%20in%20the%20return%20type%20of%20a%20method?), in the usual and recommended pattern.

**Comment by acoburn** [comment]
After #290 lands, I'll send over a PR for this.
