### ISSUE TITLE
Overall design for resources

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#292]
Following on to discussion beginning in https://github.com/trellis-ldp/trellis/pull/290.

**Comment by ajs6f** [comment]
For the [first approach](https://github.com/trellis-ldp/trellis/pull/290#issuecomment-437594080) (`Resource`s everywhere) I offer no brief at all. I don't like it, because it doesn't clearly distinguish between what the server has got and what it doesn't. I don't know what a `Resource` is, in that approach, other than a bundle of metadata and content, some or all of which may be under some kind of management, might be durable (or not), might be controlled by an ACL, who knows... 

But I'm not sure we agree on what the other approach actually is. I am _not_ suggesting that we do anything _more_ with `BinaryService` or introduce any new services. What if we were to avoid that whole question with:
```
create(Metadata m, Stream<Quad> q, IRI binary);
```
or
```
create(ResourceTemplate m, Stream<Quad> q, IRI binary);
```
(last two params in each case still nullable)? In that mode we continue to handle bitstreams just as now (directly to and from `BinaryService`).

My concern is to get metadata and content separated in the type hierarchy-- I don't as much care how we _use_ the types right now, just for this moment.

Put it this way: I suspect very strongly that our troubles are arising not because we're sending things around to the wrong places (to the contrary, I think your basic `*Service` design has held up very well) but because I think we're sending things around packed together wrongly-- in the wrong shapes and sizes of boxes with things put together that ought to travel separately _until_ the moment they fuse to become a `Resource`, and we already know where/when that happens-- with a method on `ResourceService`.

**Comment by ajs6f** [comment]
Another small point:`BinaryService` doesn't use `Binary`. The implication (to me) is that `Binary`'s semantics are weak enough that we can use an abstraction or not there, at our discretion.

**Comment by ajs6f** [comment]
Now that I think a bit more about it, I take back the `ResourceTemplate`-based version of my suggestion. If we go down the road I'm pointing at, we're not using a templating action-- we should just use a simple `Metadata` (or some other name) concrete class. No need for multiple implementations or the like, and the abstraction that I am trying to capture in that type becomes part of a `Resource` by composition, not inheritance.

**Comment by acoburn** [comment]
> Notice, interestingly, that every field is typed IRI. I'm going to try to think about why, and if we can get that nailed down as some kind of invariant.

Not so surprising given that this _is_ linked data we are dealing with, after all.

The draft interface looks very promising. Will the binary-related metadata (mime-type, size, etc) be separate?

**Comment by acoburn** [comment]
Given that the lifecycle of an LDP-NR is tied to that of its description, I would be inclined to keep the metadata combined.

The next question would be: how to model the date of an LDP-NR, which is really a question of the degree to which an LDP-NR and its description are separate resources. For example: if you create an LDP-NR at time _a_ and then modify the description at time _b_, what is the date associated with the binary? _a_ or _b_? Should the modification dates of the binary and it’s description be synchronized? Or should they be treated as two related but independent resources?

**Comment by ajs6f** [comment]
> Given that the lifecycle of an LDP-NR is tied to that of its description, I would be inclined to keep the metadata combined.

*Excellent* point.

Yes, the dates are the original thing that brought us here, no? :grin: I think we might do best here to think of some use cases for the more complex choice (independent dates). If we can't, we have no reason to do it. I personally don't think of any, except for the situation where a bitstream has been swapped for a semantically-but-not-syntactically identical form. Even then, I'm inclined to think that one would rather have a single date that is the date of the latest change to any part.

**Comment by ajs6f** [comment]
I'm inclined to think that almost any use case involving independent dates could be handled by a client-managed triple or two.

**Comment by acoburn** [comment]
@ajs6f what do you think of this: https://github.com/trellis-ldp/trellis/compare/trellis-292

It takes your initial outline and adds support for a `Binary` field. Presumably, the `Binary::getModified` method would be removed as part of this, but this is a concrete first step.

**Comment by ajs6f** [comment]
I like it-- I would want to see the pattern extended to include `Binary` itself, wouldn't you? (Meaning a builder API and its integration with the one you present above.) I suppose I would be fine with factoring the data in `Binary` into `Metadata` itself, but perhaps it's better to leave some distance there as you have, to provide ourselves with future wiggle room.

**Comment by acoburn** [comment]
Yes, let's definitely make use of the builder pattern to include `Binary`.

**Comment by ajs6f** [comment]
Hm. I wonder if we should rename `Binary`? The name sort of implies that
you can get the bitstream from it, but you can't. You _can_ get the quads
from a `Resource`, so there is also an asymmetry there. The type that
stands to `BinaryService` as `Resource` does to `ResourceService` is
actually `InputStream`.

**Comment by acoburn** [comment]
`BinaryMetadata` perhaps?

**Comment by acoburn** [comment]
in the `Resource` interface, should we also change the `getBinary` method to:

```java
public interface Resource {
    Optional<BinaryMetadata> getBinaryMetadata();
}
```

**Comment by ajs6f** [comment]
Yeah, let's close it, and if we have more discussion, let's do it under a new and less-history-burdened heading.
