### ISSUE TITLE
Corretto build

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#295]
If and when possible, it would be good to start checking a build with [Amazon Corretto](https://aws.amazon.com/corretto/) every once in a while, and eventually in CI.

**Comment by acoburn** [comment]
I already push this repo to a `remote` in AWS periodically. It should be fairly straight-forward to set up some automation to trigger a test on Corretto when that occurs.

**Comment by ajs6f** [comment]
Not a huge thing, but hey, if it's easy...

**Comment by acoburn** [comment]
Closing this as I have set up a Corretto-based CI build using AWS CodePipeline/CodeBuild, so these builds will be tested automatically whenever `master` is pushed to the AWS CodeCommit repo.
