### ISSUE TITLE
BinaryService methods

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#305]
The `BinaryService::setContent` method has two forms: `::setContent(IRI identifier, InputStream content)` and `::setContent(IRI identifier, InputStream content, Map<String, String> metadata)`.

The first just defaults to calling the second with an empty `Map`, though it is the second version of this that is actually used in the HTTP layer.

In the HTTP layer, the two bits of metadata that are added are "Content-Length" and "Content-Type", but a `BinaryService` implementation has no structured way of knowing what those keys mean. It also turns out that all of this data is exactly what's found in the `BinaryMetadata` class, so I propose the following:

1. Change `::setContent` to accept two arguments: `::setContent(BinaryMetadata metadata, InputStream input)`
2. Drop `::setContent(IRI identifier, InputStream content)`. 

A further possibility would be to add another version of that method as `::setContent(BinaryMetadata metadata, File file)`. This could default to the `InputStream` version. The HTTP layer already has a `File` object available, and some BinaryService implementations may be able to apply some optimizations when working directly with `File` objects.

What I propose is something like this:

```java
interface BinaryService {

    default CompletableFuture<Void> setContent(BinaryMetadata metadata, File file) {
        final InputStream content = new FileInputStream(file);
        return setContent(metadata, content).whenComplete((val, err) -> {
            try {
                content.close();
            } catch (IOException ex) {
                throw new UncheckedIOException("Error closing input file", ex);
            }
    }

    CompletableFuture<Void> setContent(BinaryMetadata metadata, InputStream content);

}
```

**Comment by ajs6f** [comment]
I'm basically in favor (I like that `::setContent(BinaryMetadata metadata, InputStream input)` is symmetrical with the methods in `MutableDataService`/`ResourceService`) but why is there a `File` at HTTP? I thought we were streaming bits all the way through?

**Comment by acoburn** [comment]
The HTTP layer buffers binary objects internally for three reasons.

First, in order to support [RFC 3230 Instance Digests in HTTP](https://tools.ietf.org/html/rfc3230), we need the full resource in order to compute a checksum. Yes, one could compute the checksum as the inputstream flies past, but by the time the check is complete (at which point the check may fail), the object would already have been pushed into persistence. This buffer provides some room in which to perform that check before pushing the bytes into persistence.

And second, some binary backends (e.g. AWS S3) really work best if they know the size of the resource going into the persistence layer, and I'd want the server to be managing that information (rather than relying on client-provided input, which seems problematic for several reasons).

**Comment by ajs6f** [comment]
I accept these arguments, but I understand them as conducing not to buffering the data in the HTTP layer, but to _allowing the backend to so do_.

In other words, suppose the existence of a backend for which the cost of dropping a transaction is low ( ✔️  for  `trellis-c*`) and for which the size of stream is irrelevant (✔️  for  `trellis-c*`). Why penalize all backends for the peculiarities of a few?
