### ISSUE TITLE
*-imports

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#311]
Trellis CheckStyle settings disallow the use of wildcards for imports. I think this isn't a good rule, because listing 10 or 15 JAX-RS-related imports in a class isn't clearer at all than the much shorter `import import javax.ws.rs.*`. (We could use another API for the example, but the point is the same.)

**Comment by acoburn** [comment]
The checkstyle config for this is [here](https://github.com/trellis-ldp/trellis/blob/master/buildtools/src/main/resources/checkstyle/checkstyle.xml#L70). What might make sense is to add something like, and we can add other exclusions as needed:

```xml
<module name="AvoidStarImport">
   <property name="excludes" value="javax.ws.rs"/>
 </module>
```

**Comment by ajs6f** [comment]
Yeah, that would do nicely. PR OTW.
