### ISSUE TITLE
Missing `Binary` behavior?

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#317]
If `BinaryService::get` is called with an IRI that leads nowhere, what is the correct behavior? A completed `CompletableFuture` with `null`? Something else?

**Comment by ajs6f** [comment]
I guess we'd both prefer a [null object](https://en.wikipedia.org/wiki/Null_object_pattern) to `null`.

**Comment by ajs6f** [comment]
No, I just realized-- this would end up in a 50x, wouldn't it? So we should just throw an exception. Maybe a new one specifically for the purpose, `MissingBinaryException` or something. WDYT?

**Comment by acoburn** [comment]
@ajs6f are you satisfied with the status of this issue? Is there more to discuss or can this be closed?

**Comment by ajs6f** [comment]
Yep, I'm good, but just to make a point for the future; right now I'm just throwing `RuntimeTrellisException`, but if you want to subtype it, I would rather offer an API type for that and not have multiple impl-specific exception types...

**Comment by acoburn** [comment]
Makes sense. I think we're good for now, but of course we can always revisit this if it seems like we need more specific exception types.
