### ISSUE TITLE
Change default JSON-LD serialization to compact

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#321]
At present, the JSON-LD serialization can be controlled with a `profile` parameter in an `Accept` header. When that profile parameter is absent, the default serialization is expanded JSON-LD. For most developers working with JSON, a compact serialization would be much more convenient.

I propose making the default serialization configurable via Tamaya, but absent any such configuration override, the default will be compact JSON-LD

**Comment by DiegoPino** [comment]
++++1 to compacted as default. Good improvement for non-aware clients. Thanks

**Comment by acoburn** [comment]
@DiegoPino thanks so much for the feedback!

**Comment by ajs6f** [comment]
👍
