### ISSUE TITLE
Binary hints

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#328]
Well, we took out the ability to offer persistence hints to the backend, waiting for use cases, and I finally have one. In order to potentially use `trellis-cassandra` to distribute ML tasks to bitstreams (a major focus of DRAS-TIC) we need to be able to choose an appropriate chunk-length for bitstream storage. `t-c*` can vary that on a per-resource basis, so no problem there, but there is currently no way to get that info to the backend at resource creation/replacement...

We'd need some work in the Java for this, but even more, we need to think about a way this makes sense in HTTP. I don't like the idea of magic headers, but maybe we can offer a dedicated single header. But I would much rather use a better idea!

**Comment by acoburn** [comment]
Are you thinking that these hints would be per-resource and provided by a client application (i.e. over HTTP)? Or would this be configuration defined at the server layer?

**Comment by ajs6f** [comment]
The former would be much, much better. Chunk lengths for image categorization may look nothing like chunk lengths for say, some kind of time series work.

**Comment by acoburn** [comment]
I'm not a big fan of inventing special-purpose HTTP headers, but what about adding a query parameter for this? I.e. `POST /container?binary=1MB` where the `binary` query parameter is passed along to the binary service layer.

**Comment by ajs6f** [comment]
Actually, now that I think of it, there is no reason to redo the latter option-- we can already do that. I have chunk lengths set as config now. I want them to vary as fast as resource operations, not server operations-- you see? It's a hard use case, but at least if we do it, we can feel pretty sure that we've done the whole thing and we can set a hard limit.

**Comment by ajs6f** [comment]
Hm, I don't much like query params for this because of the original semantics:
```
  The query component contains non-hierarchical data that, along with
   data in the path component (Section 3.3), serves to identify a
   resource within the scope of the URI's scheme and naming authority
   (if any).
```
We're not identifying a resource here: `binary/foo` is the same resource as `binary/foo?param=3454`. 

Here's a weird thought-- what if we don't define a header, we just guarantee that any header that the HTTP layer doesn't consume will be passed back to the backend in a `Multimap`? There's a DOS vector there, but we could just truncate header values after 1k or something, and any problems that arise from misusing tainted data are on the backend, not the framework.

**Comment by acoburn** [comment]
That's an interesting idea. It frees us from having to define the semantics around particular headers while still allowing implementation-specific behavior.

**Comment by ajs6f** [comment]
Exactly, we only take responsibility for transport, not use.

**Comment by acoburn** [comment]
With #327, I add this method to `TrellisRequest`: `MultivaluedMap<String, String> getHeaders()`, which we could just pass directly into the `BinaryService`.

**Comment by ajs6f** [comment]
:wind_chime:

Wind chime is as close as I could find to "CH-CHING".

**Comment by acoburn** [comment]
We'd just want to cast that as a `Map<String, List<String>>` so as not to pull in all of JAX-RS to the API layer

**Comment by ajs6f** [comment]
Or use a third-part `Multimap`, but I have no problem with `Map<String, Collection<String>>`. Maybe a `Set`?

**Comment by acoburn** [comment]
It's just that `MultivaluedMap<K, V> extends Map<K, List<V>>`, so rather than reallocating memory for the data structure, we could just pass along the reference.

**Comment by ajs6f** [comment]
I am a-ok with that! Besides, I suppose the most honest thing is not to drop duplicates.
