### ISSUE TITLE
hints for Binary identifiers?

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#331]
The method `BinaryService::generateIdentifier` currently takes no arguments, but in the context of adding hints to the `BinaryService`, should we add a parameter to that method, accepting a (nullable) IRI corresponding to the associated Resource identifier? An implementing service can do whatever it wants with that value (including ignoring it), but it _could_ influence how internal identifiers are generated. I don't have any use for this in any of the existing implementations, but I can imagine that one might want to store binaries in locations that relate to where the resource itself is stored.

**Comment by ajs6f** [comment]
Hm. Do we want to preemptively offer machinery by which people can make themselves those kinds of guarantees? They can do it now (impl an `IdentifierService` with an extra method to be called specifically by your `BinaryService::getIdentifier`) but they have to damn well know they're doing it. I would rather to see some concrete use cases.

Another approach: specialize and invert `IdentifierService`. Have a `BinaryIdentifierService` and a `ResourceIdentifierService` and let people impl them together or separately or however they like, but have the default choice impl them both with the same UUID mint, much like `MutableDataService` and `ImmutableDataService` are commonly expected to be implemented together as `ResourceService`.

**Comment by acoburn** [comment]
I agree. I'm going to close this issue.
