### ISSUE TITLE
Upgrade to Tamaya 0.4

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#337]
When Tamaya 0.4 is released, the code should be updated to use the new API.

**Comment by ajs6f** [comment]
@acoburn -- as a committer, can you start this discussion with Tamaya? Or is there already a process underway?

**Comment by acoburn** [comment]
Yes, I was planning open this discussion immediately after the holidays.

**Comment by ajs6f** [comment]
👍

**Comment by acoburn** [comment]
Superseded by #366
