### ISSUE TITLE
Missing TestUtils?

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#339]
After pulling https://github.com/trellis-ldp/trellis/commit/a0e26a1e2dd4c8ded4c87a8ad8d47d93f5f2d985, my tests in `trellis-cassandra` that are just subtypes of the tests in `trellis-test` are now throwing a bunch of
```
[ERROR] edu.si.trellis.cassandra.LdpBasicContainerIT  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.trellisldp.test.TestUtils
	at org.trellisldp.test.LdpBasicContainerTests.beforeAllTests(LdpBasicContainerTests.java:83)
```
Any thoughts? Seems a bit baffling, because there it is in the JAR...

**Comment by acoburn** [comment]
From the line number hints, I think that the problem was [here](https://github.com/trellis-ldp/trellis/blob/a0e26a1e2dd4c8ded4c87a8ad8d47d93f5f2d985/components/test/src/main/java/org/trellisldp/test/TestUtils.java#L150) where the function in `TestUtils` is trying to reference the `CommonTests` class (it should reference `TestUtils`). I suspect that this is an artifact of moving code around, though I don't know why it would appear now. I added a commit that should fix this: c8351f1143e97846420d8e377c5b98fd3bb691c5

**Comment by ajs6f** [comment]
I'm afraid not... still getting
```
java.lang.NoClassDefFoundError: Could not initialize class org.trellisldp.test.TestUtils
	at org.trellisldp.test.CommonTests.checkCreateResponseAssumptions(CommonTests.java:102)
	at org.trellisldp.test.LdpBinaryTests.beforeAllTests(LdpBinaryTests.java:84)
```

**Comment by ajs6f** [comment]
Incidentally, the code that is having this problem is in the branch:

https://github.com/ajs6f/trellis-cassandra/tree/TestOddity

(My `master`, of course, won't build against Trellis `master` because of our recent changes.)

**Comment by ajs6f** [comment]
[This build](https://circleci.com/gh/ajs6f/trellis-cassandra/138) shows it.

**Comment by acoburn** [comment]
I think the -test module is missing a dependency on commons-io. If you were to add include that dep in your pom.xml, would that fix the issue? I will plan to add the missing dependency in the AM to the -test module.

**Comment by ajs6f** [comment]
Nope, no change at all. This is really weird!

**Comment by acoburn** [comment]
The error points to the `TestUtils` class, and that class has a static initializer for JenaIO, which in turn has a static initializer for Tamaya. This was changed recently with this commit https://github.com/trellis-ldp/trellis/commit/4c040749f5744f87b470bcdb38844aab7c5fd86a. When I reverted that commit for the JenaIO module, the tests in your branch of TC* pass.

In a few moments I'll push the reverted commit to github.

**Comment by acoburn** [comment]
@ajs6f can you give this a try now?

**Comment by ajs6f** [comment]
Just finished doing that-- we're good.

**Comment by ajs6f** [comment]
Thanks!
