### ISSUE TITLE
Upgrade to Jena 3.10

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#344]
Jena 3.10.0 is currently being voted on. Once released, Trellis should start using it (I've already verified that the tests pass with the release candidate).

**Comment by ajs6f** [comment]
Are we getting much advantage from Commons RDF? Do we have any components that aren't using Jena as impl?

**Comment by acoburn** [comment]
Everything uses Jena, so no, we aren’t getting much benefit from Commons in that sense. I do think there is some advantage to keeping that abstraction, but I am not wedded to that opinion. Removing CommonsRDF would be pretty far-reaching.

**Comment by ajs6f** [comment]
Yep, good and bad-- bad if you do want to use something else, good in that it would cut a lot of short-lived objects out of the VM. I'm not going to make a big push for this now. I will bring it up more strongly if @gregjan's testing indicates that GC pauses are a real performance problem. We haven't seen any evidence of that yet, have we?

**Comment by acoburn** [comment]
It would be telling if we could do some side-by-side performance testing with and without commons RDF. Maybe something to try in the late Winter/early Spring?

**Comment by ajs6f** [comment]
Yeah, that would be the ultimate test. I'd be up for that, once @gregjan is happy with the basic layers of data.
