### ISSUE TITLE
Replace `CompletableFuture` with `CompletionStage`

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#345]
We return `CompletableFuture` extensively throughout the API, because we like the ability it offers to chain computation. But those methods actually come from `CompletionStage`. `CompletableFuture` adds only the ability to complete the future with a value or `Throwable`, which is actually not at all something we want, for the API. I can't imagine a situation in which the HTTP layer correctly completes a `Future` it retrieved from the backend-- can you?

We should replace all the slots now holding `CompletableFuture<X>` with `CompletionStage<X>`. This will require _no_ other changes, since `CompletableFuture<X> extends CompletionStage<X>`.

**Comment by acoburn** [comment]
This change makes sense to me. Plus, if one really needs a `CompletableFuture<T>`, one can always call `CompletionStage::toCompletableFuture`.

Let's get this into the 0.8 series -- I'll provide a PR in the next day or so.
