### ISSUE TITLE
ETag vs. Memento

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#346]
When a resource is added to a container, the modified-date of that container gets bumped (via `ResourceService::touch`) which bumps the `ETag` of that container.

Should this mean a new Memento of that container? I've been avoiding that with some updating gymnastics (new "child" ≠ new Memento for container), but am I doing right? Is a new "child" a sufficient change to indicate a new "version" (whatever that means)?

**Comment by acoburn** [comment]
On this issue, the implementation has some flexibility. I have typically chosen _not_ to create new mementos for a parent container when a child resource is created. For example, if a Memento on the parent is created with the creation of each child resource, the parent will then have at least as many memento headers _on every request_. That is, if the parent has 100K child resources, a simple HEAD request for the parent will return at least 100K memento headers, which seems like a whole lot of transport overhead.

**Comment by ajs6f** [comment]
Agreed, and that's why I did the same. So this is actually a documentation ticket. I'm not sure where to document that-- class Javadocs for `ResourceService`?

**Comment by acoburn** [comment]
The class Javadocs for `MementoService` might make more sense. Or maybe some additional text in both?

**Comment by ajs6f** [comment]
What about a comment on `MementoService::put`? Looking at this again after some weeks, it seems to me that that's where the action is...

**Comment by acoburn** [comment]
Yes, a comment in `MementoService::put` would be great.

**Comment by acoburn** [comment]
@ajs6f do you feel that this issue is now resolved? Or is there more documentation coming?

Thanks

**Comment by ajs6f** [comment]
Oops!
