### ISSUE TITLE
Add notification components/configuration to app

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#35]
This will include AMQP, JMS and Kafka clients.

**Comment by acoburn** [comment]
Part of this issue will be to write a "null client" that does nothing when emitting an event. This would be for the case where messaging is disabled. It will also mean that the TriplestoreResourceService will no longer accept a `null` value for the `EventService` parameter. This is all in preparation for supporting CDI (at present, various `*Service` implementation constructors will accept `null` values for "optional" parameters, but that is problematic for simple JSR 330 `@Inject` wiring) and this can all be easily mitigated by writing such "null implementations".

**Comment by ajs6f** [comment]
How are we using the term "client" here? It seems like a component that _emits_ messages?

**Comment by acoburn** [comment]
Client is a misnomer; I was thinking of the existing notification service components, each of which wraps a particular client. This "null client" wouldn't have a client at all -- it would be better (as you phrase it) to refer to this as a component. I will update the title of the issue to reflect that.

**Comment by ajs6f** [comment]
Cool-- I get what you mean now. I think the "null component" pattern is going to be incredibly useful, and if we design and code right, we could potentially make the "null component" in a given role be a convenient supertype for other components in that role. That's been difficult with the `AuditService` example, but we're still evolving that section.
