### ISSUE TITLE
Test failures in branch

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#357]
Trying to build this [branch](https://github.com/trellis-ldp/trellis/tree/branch-trellis-349) I'm getting (s/`IT`/`Test`):
```
[ERROR] Failures:
[ERROR]   LdpBasicContainerIT.testCreateContainerViaPut Check for an ldp:contains triple ==> expected: <false> but was: <true>
[ERROR]   MementoBinaryIT Check for a valid response to PUTting an LDP-NR ==> expected: <SUCCESSFUL> but was: <CLIENT_ERROR>
[ERROR]   MementoResourceIT Check for a valid response to PUTting an LDP-NR ==> expected: <SUCCESSFUL> but was: <CLIENT_ERROR>
[ERROR]   MementoTimeGateIT Check for a valid response to PUTting an LDP-NR ==> expected: <SUCCESSFUL> but was: <CLIENT_ERROR>
[ERROR]   MementoTimeMapIT Check for a valid response to PUTting an LDP-NR ==> expected: <SUCCESSFUL> but was: <CLIENT_ERROR>
[INFO]
[ERROR] Tests run: 30, Failures: 5, Errors: 0, Skipped: 1
```
Some look like interaction between Memento and the new JAX-RS resources, tho' not the first. I've not yet gone into them. Before I do, does anything strike you?

**Comment by acoburn** [comment]
As for the `testCreateContainerViaPut` method, that is not surprising -- with WebDAV, when a new resource is added to a container (i.e. directory) it is done so with PUT. In Trellis, however, PUT does not add containment information on the parent container, so [this code](https://github.com/trellis-ldp/trellis/blob/branch-trellis-349/components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAVRequestFilter.java#L69-L76) rewrites any PUT to a non-existent resource as POST with an appropriate Slug header. PUT to an extant resource is passed through as PUT.

As for Memento, the code completely ignores memento at the moment. There are a bunch of `TODO` statements such as [this one](https://github.com/trellis-ldp/trellis/blob/branch-trellis-349/components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAV.java#L169).

**Comment by ajs6f** [comment]
Okay, so for my (non-Memento-using) testers, no problem. I'll deploy and we'll see what we get.
