### ISSUE TITLE
Consider removing support for Want-Digest

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#359]
The `Digest` and `Want-Digest` features stem from an arguably problematic assumption that an HTTP-based software stack should be responsible for checking the bits in a persistence layer. There are better and more efficient ways to do this, such as checking the persistence layer directly.

**Comment by ajs6f** [comment]
This is not an SI use case at all. We would be happy to discard this function.

**Comment by acoburn** [comment]
If this is truly needed _in software_, it can easily be implemented by some external layer.
