### ISSUE TITLE
Membership triples tests for basic containers

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#372]
Tests for basic containers should ensure that they do not produce membership triples.

**Comment by acoburn** [comment]
Actually, a basic container _can_ generate membership triples if the LDP-BC is the target of an `ldp:membershipResource` (i.e. from a separate LDP-DC).

For example,
given this LDP-DC: /a-direct-container
```turtle
</a-direct-container> ldp:membershipResource </a-basic-container> ;
      ldp:hasMemberRelation ldp:member ;
      ldp:contains </a-direct-container/child1> , </a-direct-container/child2> , </a-direct-container/child3> .
```

Then the corresponding basic container would include these membership triples:

```turtle
</a-basic-container> ldp:member </a-direct-container/child1> , </a-direct-container/child2> , </a-direct-container/child3> .
```

```

**Comment by ajs6f** [comment]
Is that a use case we want to support? That seems slightly demented to me...

**Comment by acoburn** [comment]
Demented or not, it's a use case that is described by the [LDP spec](https://www.w3.org/TR/ldp/) itself. Take a look at example 4, 6, 8 and 10. In those instances, the membership resource is a separate RDFSource, but there is no reason that the membership resource couldn't be a container of some type.

**Comment by ajs6f** [comment]
Well, demented seems too strong now, and I'm sorry I used it, but it's exactly the membership resource being a container that is at stake, so I don't think those examples argue for this pattern.

In any event, for this ticket all we need do is agree on normative behavior for _some_ cases and write that down as tests. That can be added to what we have, so it would be an improvement, right?

**Comment by acoburn** [comment]
In the construction of the test resources, we can create a basic containment structure which _shouldn't_ contain any membership triples. We can then test that no such triples appear. In fact, there are several tests that build up this structure, so it should be easy to add tests for the absence of membership triples. For example: fetch a basic container using prefer headers, accepting _only_ Membership triples, this should return an empty RDF document.
