### ISSUE TITLE
Return type from Resource::stream

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#374]
There are three variations to the `Resource::stream` method:

```java
Stream<Quad> stream();

Stream<Triple> stream(Collection<IRI>);

Stream<Triple> stream(IRI);
```

What if all of these methods returned a `Stream<Quad>`? I think this would make the interface more consistent.

**Comment by ajs6f** [comment]
I'm not sure how `Stream<Triple> stream(Collection<IRI>);` makes sense anyway, because how do you distinguish between the various named graphs you get back?
