### ISSUE TITLE
PATCH requests with absolute in-domain URIs are not correctly mapped to resource graphs

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#386]
Given a resource:

```turtle
<> a ex:Foo ;
    dc:title "A title" .
```

The SPARQL-Update request to delete these triples only works with relative URIs:

```
DELETE DATA {
  <> dc:title "A title" .
}
```

With absolute URIs, the delete statement does not match the resource triples (and the triples are not removed). This is due to the fact that when the resource triples are loaded into a `Graph` in preparation for running the `IOService::update` operation, the triples are not first converted from their internal representation to an external representation and the context of the update query uses the internal IRI value (rather than the external resource URL).

**Comment by mjgiarlo** [comment]
@acoburn Related to this issue, if the root ACL resource looks like:

```ttl
<http://platform:8080/#auth>
        acl:mode        acl:Read ;
        acl:mode        acl:Write ;
        acl:mode        acl:Control ;
        acl:agentClass  <http://xmlns.com/foaf/0.1/Agent> ;
        acl:accessTo    <http://platform:8080/> .
```

And I want to replace it with my own ACLs, I would think I could issue a PATCH request to `http://myhost:myport/?ext=acl` with the following SPARQL Update:

```sparql
DELETE DATA {
     </#auth>
        acl:accessTo    </> ;
        acl:agentClass  <http://xmlns.com/foaf/0.1/Agent> ;
        acl:mode        acl:Control ;
        acl:mode        acl:Write ;
        acl:mode        acl:Read .
}
```

The response seems to succeed (returns a 204), but the graph is unaltered. Am I doing something obviously wrong or is this a bug? (I am rusty with SPARQL, fair warning.)

**Comment by acoburn** [comment]
The SPARQL request that I'd use is this:

```sparql
PREFIX acl: <http://www.w3.org/ns/auth/acl#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

DELETE WHERE { ?s ?p ?o };
INSERT {
  </#my_auth>
        acl:accessTo    </> ;
        acl:agentClass  foaf:Agent ;
        acl:mode        acl:Control , acl:Write, acl:Read .
} WHERE {}
```

**Comment by mjgiarlo** [comment]
@acoburn That worked like a charm once I reworked the triples in the `INSERT` block to be ntriples rather than turtle. thank you!
