### ISSUE TITLE
building membership and containment messages with TriplestoreResourceService?

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis#39]
From what I can gather, the TripleStoreResourceService is publishing notifications to a single configured topic (default "trellis").   This is different than the FileResourceService that has an EventProducer to build containment and membership messages that are published to distinct topics read by the async processor. 

Not clear to me with TripleStoreResourceService how this works.  In brief evaluation today, there does not seem to be a "built-in" mechanism to do this in trellis-app yet.  Is this accurate?   Can you explain the design intent for this briefly?  Thanks!

**Comment by acoburn** [comment]
The main difference between the Triplestore implementation and the Kafka-based implementation is that the Triplestore one is strongly consistent (no async processor) and single-node. The primary design intent here is simplicity of deployment and simplicity of implementation, not scalability.

So when it comes to notifications, the only notifications that need to be published are the ones for resource changes. With the kafka-based impl, containment and membership triples are modified asynchronously, so there are intermediate topics that the async processor handles.

**Comment by christopher-johnson** [comment]
I have noticed now that <http://purl.org/dc/terms/isPartOf> describes a containment hierarchy in the triplestore.   Does this relate to LDP membership in the server managed data model?   Sorry if I seem confused, but what is required for one to get LDP membership triples with the TripleStoreResourceService?

**Comment by acoburn** [comment]
Membership triples are retrieved dynamically via SPARQL query on the dataset/triplestore. You can see examples of this in the code.

[Indirect containers](https://github.com/trellis-ldp/trellis/blob/master/trellis-triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResource.java#L304-L350)

[Indirect containers with ldp:MemberSubject](https://github.com/trellis-ldp/trellis/blob/master/trellis-triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResource.java#L352-L392)

[Direct containers](https://github.com/trellis-ldp/trellis/blob/master/trellis-triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResource.java#L394-L431)

[Direct containers with inverted membership](https://github.com/trellis-ldp/trellis/blob/master/trellis-triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResource.java#L433-L471)

**Comment by christopher-johnson** [comment]
Right, I see the logic to retrieve them, but how are they created?  In my test, I do not see any LDP predicates so I am wondering if I need to do something differently than before?  Everything else works great!

**Comment by acoburn** [comment]
There are a number of queries in the [TriplestoreResourceService](https://github.com/trellis-ldp/trellis/blob/master/trellis-triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java) that set these values. That said, I also haven't written any end-to-end tests for membership triples, so it is entirely possible (read: quite likely) that there are bugs in the code.

**Comment by christopher-johnson** [comment]
I have an idea why this happened.  The "parent" resource in my test does not have an `ixnModel` so the code in TriplestoreResourceService that creates the membership triples is not reached because it is expecting [either a Direct or Indirect Container](https://github.com/trellis-ldp/trellis/blob/master/trellis-triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java#L151).  

Is not the conventional expectation that LDP-RSs are created using the LDPC interaction model by default?   Also, the code is checking for Direct or Indirect, but not Basic.   

I assume the syntax to explicitly create a Direct Container would be something like this:
`curl -i -X PUT -H 'Link: <http://www.w3.org/ns/ldp#DirectContainer>; rel="type"' "http://localhost:8080/some/direct/container"`, yet this returns a 409 because of InvalidCardinality...

**Comment by acoburn** [comment]
Yes, the LDP spec has some required properties for Direct Containers:

```turtle
<> ldp:membershipResource <#some-resource> ;
  ldp:hasMemberRelation ex:someRelationship .
```

Or:

```turtle
<> ldp:membershipResource <#some-resource> ;
  ldp:isMemberOfRelation ex:otherRelationship .
```

For Indirect containers, you will also need the `ldp:insertedContentRelation` triple. And those triples need to be there when you create/update the resource on PUT or POST.

**Comment by christopher-johnson** [comment]
It seems that LDP-DC can be created with POST, but not with PUT.  

Example:
```bash
curl -i -X POST -H 'Link: <http://www.w3.org/ns/ldp#DirectContainer>; rel="type"' -H 'Content-Type: text/turtle' --data-binary @ldp-direct.ttl -H 'slug: child' "http://trellis:8080/" 
```
with body:
```turtle
@prefix ldp: <http://www.w3.org/ns/ldp#>
@prefix bt: <http://example.org/vocab/bugtracker#> .

<> ldp:hasMemberRelation bt:hasBug ;
ldp:membershipResource <http://trellis:8080/123> .
```
works, but 
```bash
curl -i -X PUT -H 'Link: <http://www.w3.org/ns/ldp#DirectContainer>; rel="type"' -H 'Content-Type: text/turtle' --data-binary @ldp-direct.ttl -H 'slug: child' "http://trellis:8080/"
```
returns a 409
```bash
DEBUG [2018-02-07 11:07:41,267] org.trellisldp.constraint.LdpConstraints: Constraint violation: http://www.trellisldp.org/ns/trellis#InvalidRange: [<trellis:data/> <http://www.w3.org/ns/ldp#membershipResource> <trellis:data/123> .]
```
Could be related to baseUrl being passed to checkConstraint instead of TRELLIS_DATA_PREFIX?

**Comment by acoburn** [comment]
@christopher-johnson I wrote a full test for direct containers using `POST` (see https://github.com/trellis-ldp/trellis/commit/7c3b959d25cbf6950a84d1431375b26825f657e8), and everything works fine. However, in writing an equivalent test with `PUT` I am encountering the same issue you are reporting here. I'll work on fixing that now -- thanks for the report!

**Comment by acoburn** [comment]
@christopher-johnson your suggestion was exactly correct: the `checkConstraint` method was being called with `baseUrl` instead of `TRELLIS_DATA_PREFIX`.
