### ISSUE TITLE
Collections utils library

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#394]
We've got a considerable amount of collections-munging boilerplate in the codebase now. A typical example might be building unmodifiable sets or maps for constants. @acoburn has mentioned his discomfort with depending on Guava, which I share, but we have an alternative in Apache Commons Collections. We already make any deployable depend on a host of Commons libraries (`io`, `codec`, `text`, a bunch of others).

Is there a way we can make the utility of Commons Collections available in the upper layers (e.g. in the WebDAV module, which is where I happened to be when I began thinking about this) without pushing it down too far towards the API? I don't understand enough about Gradle to guess.

**Comment by acoburn** [comment]
My opinion is that, for any modules in the `./components` section, Guava (or Commons Collections) is fine. I do really like using Guava, but I would just try to keep it out of the `./core` modules.

**Comment by ajs6f** [comment]
That sounds like a great "middle ground". In a Maven build, I would add the dependency to a `pom.xml` for `./components`. Do we have an option like that in Gradle?

**Comment by acoburn** [comment]
We already track the guava version we use in the main `./build.gradle` file [here](https://github.com/trellis-ldp/trellis/blob/master/build.gradle#L38). Then, in the particular component library with the guava dependency, add a dependency definition to the `./build.gradle` file sort of like [this](https://github.com/trellis-ldp/trellis/blob/master/components/webdav/build.gradle#L20), though with the Guava coordinates.

**Comment by ajs6f** [comment]
Okay, so it has to be on a per-component basis? Do you have a preference between Guava and Commons? For the kinds of uses of which I am thinking, they are each about equally useful.

**Comment by acoburn** [comment]
I'd probably go with Guava.

**Comment by ajs6f** [comment]
Works for me. I'll mess with this after another round of grinding on `Optional` and friends.

**Comment by ajs6f** [comment]
This should build on https://github.com/trellis-ldp/trellis/pull/395 so I'll wait for that to be merged before fooling with this.

**Comment by acoburn** [comment]
👍
