### ISSUE TITLE
Make TrellisUtils::findFirst package-private

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#396]
This [commit](https://github.com/trellis-ldp/trellis/commit/39a7704e3e2ff5ef1fa640af330cc9e17a62333c) makes `TrellisUtils::findFirst` public and extends its use to other modules, as it had been some time ago, but this breaks the JPMS build because then the API module would _technically_ need to declare a `uses` clause in the `module-info.java` file for every interface that makes use of that method. And doing that would make the actual use of this incredibly cumbersome. Instead, the code that now makes use of that method should be refactored to use something else (i.e. a private method implemented in its own module). This will result in more code duplication, but I don't see a reliable way around this.

**Comment by ajs6f** [comment]
Urm. Okay, I'll come back to this probably sometime next week. I have yet to hear anyone have anything good to say about JPMS, and I'm not holding my breath.

**Comment by acoburn** [comment]
I can take care of this, and I hear you about JPMS: I'm still waiting to be convinced.

**Comment by ajs6f** [comment]
Thanks!
