### ISSUE TITLE
Errors with no logging

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#397]
I'm switching `t-c*` over to use a design for Mementos much like what the other backends use, but I'm seeing some strange error behavior. Specifically, I'm getting `SERVER_ERROR` responses to the test client, with no ERROR logging at all. Below are some examples of the tests that are bombing. Am I correct to think that I should be seeing logs of whatever errors are occurring? It's not easy to see how to debug with no information at all… Of course I can post some logs somewhere if that is useful, but I do have Trellis' logging up to DEBUG.

```
[ERROR] Failures:
[ERROR]   MementoResourceIT.testMementoAcceptDateTimeHeader Check that the memento-datetime header is correct ==> expected: <2019-05-06T20:08:41Z> but was: <2019-05-06T20:08:39Z>
[ERROR]   MementoResourceIT.testMementoAllowedMethods Check allowed methods (4 failures)
	Check for a successful response ==> expected: <SUCCESSFUL> but was: <SERVER_ERROR>
	GET should be allowed! ==> expected: <true> but was: <false>
	HEAD should be allowed! ==> expected: <true> but was: <false>
	OPTIONS should be allowed! ==> expected: <true> but was: <false>
[ERROR]   MementoResourceIT.testMementoDateTimeHeader Check for a successful memento request ==> expected: <SUCCESSFUL> but was: <SERVER_ERROR>
[ERROR]   MementoResourceIT.testMementoLdpResource Check LDP headers (3 failures)
	Check for a successful response ==> expected: <SUCCESSFUL> but was: <SERVER_ERROR>
	<no message> in java.lang.NullPointerException
	<no message> in java.lang.NullPointerException
```

**Comment by acoburn** [comment]
There should be at least two sets of logs in play. The logging that is shown above is coming from the test suite, but what you really need are the logs from the application itself. Is there a way to turn up the logging from the T-C* application itself? Or perhaps does that application write to a separate log location?

**Comment by ajs6f** [comment]
I'm sorry-- I was referring to the system logs. That's where there is no ERROR logging occurring. I realize that the test apparatus isn't going to log the errors (other than noting that the test failed). Sorry for the confusion!

**Comment by acoburn** [comment]
In principle, any exceptions should be logged [here](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/TrellisHttpResource.java#L431-L437) unless they are caught somewhere in the implementation code. Perhaps we should add some more debug logging at this point in the HTTP layer

**Comment by ajs6f** [comment]
That's pretty weird. Just for grins, I'll try running against your new commit and see if I get anything…

**Comment by acoburn** [comment]
I'm not entirely sure that this commit will even help, since it only adds DEBUG logging to exceptions that are client errors (4xx) or redirection "errors" (3xx). All other exceptions should already be logged at the ERROR level.

**Comment by ajs6f** [comment]
I know, that's what's weird. There may be something wrong with my logging setup, so I'll investigate all avenues.

**Comment by ajs6f** [comment]
[Here's](https://gist.github.com/ajs6f/54ed4176f6b52140717cc6a3e46f70e9) a gist of the log for that wacky test. Tons of DEBUG-level logging, but no ERRORs.

**Comment by ajs6f** [comment]
Hang on, it was indeed a problem with my logging setup, or at least something very strange. The errors are getting logged, but in the test logging. Not sure why, but at least they are there. Closing.
