### ISSUE TITLE
Relationships among deployable artifacts

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#403]
We have a few deployable artifacts already in play, and we are looking to remove some (Dropwizard-based app) and add some (µProfile-based app). `trellis-cassandra` maintains its own independent app and Docker machinery. That's not ideal. 

Do we want to commit to a certain set of deployment options and make them available in same way for every backend? Obviously, this could get a bit tricky. It might mean crossing lines between wiring and packaging. But I think we should try thinking through this, at least.

**Comment by acoburn** [comment]
Yes, we should definitely think about this, and I'm open to suggestions. What I've done for the dropwizard-based artifacts is create a "generic" `trellis-app` artifact, which pulls together most of what's needed for a deployable application. We could do something similar with microprofile. Or if you have some different ideas, I'd be open to that.

**Comment by ajs6f** [comment]
Yeah, that's along the lines of which I was thinking, but if we want to support more than one backend, we will have to get into some means by which to select one. Or do we just issue another app artifact and Docker artifacts for every backend? With only a few "officially" supported, I think we could actually do that. It's when we add in the combinations of `WebAC`, event publishing, etc., that things begin to look a bit intractable to me.

**Comment by acoburn** [comment]
I would hope that we'd not need separate artifacts for all these permutations. Ideally, we'd control these components with some sort of configuration (which is how the `trellis-app` artifact handles this), but that might require some experimentation.

**Comment by ajs6f** [comment]
Well, that takes us back to a traditional Trellis topic; the relationship between wiring and config. It's not clear to me right now how to make Tamaya config drive CDI injection. I'll have to think about that.
