### ISSUE TITLE
Move all WebAC code into its own module

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#417]
At present, WebAC authorization is split between the WebAC authorization implementation (`trellis-webac`) and the HTTP request filter (`http.WebAcFilter`). By consolidating all of the WebAC-related code in the `trellis-webac` module, we should be able to eliminate the `api.AccessControlService`, since that service will be more self-contained. The only possible sticking point concerns the `trellis-webdav` module and how WebAC gets applied to those WebDAV-specific methods.

See also the discussion [here](https://github.com/trellis-ldp/trellis/issues/209#issuecomment-501832349)

**Comment by ajs6f** [comment]
Can you parse out the relationship between WebDAV and WebAC a bit? I'm running an instance with WebDAV but not WebAC, so that's one possibility. If they are both present, is the interaction well-defined? I can't imagine WebAC discusses WebDAV-specific methods, but I would love to be wrong.

**Comment by acoburn** [comment]
The [`TrellisWebDAVAuthzFilter`](https://github.com/trellis-ldp/trellis/blob/master/components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAVAuthzFilter.java#L48) inherits from `http.WebAcFilter`, applying the authorization filters to the methods defined [here](https://github.com/trellis-ldp/trellis/blob/master/components/webdav/src/main/java/org/trellisldp/webdav/TrellisWebDAVAuthzFilter.java#L51-L53). I may change my opinion after I try implementing this, but it seems as though all of the logic defined in `TrellisWebDAVAuthzFilter` can just become part of the request filter that lives in `trellis-webac`.

**Comment by ajs6f** [comment]
The JAX-RS methods are non-interfering according to the appropriate resolution rules (or it wouldn't work and it does) which makes this extremely plausible. You might want to still offer two filters, so that people who don't want WebDAV can easily select just what they need.

**Comment by gregjan** [comment]
I ran into this one when I tried to inject a WebAcFilter and it came back as ambiguous due to the inheritance by the WebDav filter class. I'm omitting webdav for the moment.
