### ISSUE TITLE
audit info inclusion

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#42]
Does Trellis take the stance of adding audit info to a response unless told otherwise, or only adding it if told to (by a `Prefer` header)? I know I could trace out the code and see what it currently does, but I want to make sure I understand why.

**Comment by acoburn** [comment]
The current stance is to return user-managed, membership and containment triples for an RDF-based resource. Audit triples are returned only if requested via Prefer header:

```http
Prefer: return=representation; include="http://www.trellisldp.org/ns/trellis#PreferAudit"
```

**Comment by ajs6f** [comment]
Okay, cool. I'm still banging around on #31 , and this helps me understand how to make sure HTTP is connected to persistence.
