### ISSUE TITLE
SNAPSHOTs?

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#423]
Are the artifacts being built out of CI (currently at `0.9.0-SNAPSHOT`) being reposited anywhere? I'm just curious as to whether I can avoid building them off-line.

**Comment by acoburn** [comment]
Yes, snapshot artifacts are pushed to Sonatype via CI pipelines on each commit. For example, `trellis-api` is available here: https://oss.sonatype.org/content/repositories/snapshots/org/trellisldp/trellis-api/0.9.0-SNAPSHOT/

The build code (gradle) for this is configured here: https://github.com/trellis-ldp/trellis/blob/master/build.gradle#L361-L362

And the CI configuration for this is here: https://github.com/trellis-ldp/trellis/blob/master/.travis.yml#L70-L77

**Comment by ajs6f** [comment]
Excellent, thanks!
