### ISSUE TITLE
Relocate ServiceBundler from api to http layer

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#442]
All uses of the ServiceBundler are at the HTTP layer or higher, and in order to use the interfaces defined at the HTTP layer (e.g. `TimemapGenerator`, `EtagGenerator`) we would either need to bring those interface into the API layer or move the ServiceBundler into the HTTP layer.

I propose moving `ServiceBundler` into the `org.trellisldp.http.core` package.

This would be a prerequisite to working on #441

**Comment by ajs6f** [comment]
👍
