### ISSUE TITLE
Create default implementations for http.core interfaces

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#449]
Two new interfaces in the http layer (`http.core.EtagGenerator` and `http.core.TimemapGenerator`) have no default implementations, which makes it harder to use these as injectable CDI beans, especially since they are now required parts of the `ServiceBundler` interface.

Related question: should these beans have a `@Default` and/or `@ApplicationScoped` annotation assigned?

**Comment by ajs6f** [comment]
Unless there is more than one potential choice for a default, there is no need for `@Default`. A bean with no other qualifier is (by default 😁  ) automatically qualified as `@Default`. `@ApplicationScoped` sounds correct, as long as these beans are indeed expected to last for the lifetime of the application.
