### ISSUE TITLE
Review annotation on DefaultIdentifierService

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#451]
Recently, I added the `@Alternative` [annotation](https://github.com/trellis-ldp/trellis/blob/master/core/api/src/main/java/org/trellisldp/api/DefaultIdentifierService.java#L30) to the `DefaultIdentifierService`. Should that annotation be removed so that it really acts as a `@Default`? or should it stay in place to make it easier to override?

**Comment by ajs6f** [comment]
I would remove it. If we need a new annotation for default stuff like that we can certainly create one (a stereotype, like what we did for no-op impls). But do we not expect that most folks would be perfectly happy with the `DefaultIdentifierService`? If so, qualifying it as `@Alternative` is really misleading, and we don't expect overriding it to be common.
