### ISSUE TITLE
Normalize class names

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#461]
The various no-op service implementations all follow a standard naming convention: `org.trellisldp.<module>.NoopXService`, but the other service implementations really don't.

We have some `DefaultXService` classes, and several backend-specific classes (e.g. `TriplestoreResourceService`. Those are fine, but others ought to be reviewed.

As such, I'd like to propose the following changes:

```
o.t.agent.SimpleAgentService         =>  o.t.agent.DefaultAgentService
o.t.rdfa.HtmlSerializer              =>  o.t.rdfa.DefaultRdfaWriterService
o.t.event.EventSerializer            =>  o.t.event.DefaultActivityStreamService
o.t.constraint.LdpConstraints        =>  o.t.constraint.LdpConstraintService
o.t.ampq.AmqpPublisher               =>  o.t.amqp.AmqpEventService
o.t.jms.JmsPublisher                 =>  o.t.jms.JmsEventService
o.t.kafka.KafkaPublisher             =>  o.t.kafka.KafkaEventService
o.t.namespaces.NamespacesJsonContext =>  o.t.namespaces.JsonNamespaceService
```

Other suggestions are welcome.

**Comment by ajs6f** [comment]
👍 except `DefaultConstraintService`. I think `LdpConstraintService` is more descriptive. The fact that it is on by default isn't as important as the fact that it provides a lot of LDP behavior.

**Comment by acoburn** [comment]
I like your suggestion. I'll update the proposal to use `LdpConstraintService`
