### ISSUE TITLE
Reduce scope of osgi module

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#463]
The `trellis-osgi` module is currently used to test whether the various trellis components are deployable within an OSGi system. There is also code present that may imply that an entire Trellis application is deployable in OSGi, which is neither true nor a goal at present. Yet as long as that code is present, it needs to be maintained.

I would like to propose removing all code in `./osgi/src/main`.

**Comment by ajs6f** [comment]
👍
