### ISSUE TITLE
Accept-Datetime should return the closest Memento

### ISSUE THREAD

**Issue by gregjan** [trellis-ldp/trellis#465]
According to RFC 7089, section 4.5.3, the Accept-Datetime header can request a date from a TimeGate prior to the first memento or after the last memento. In these cases, the specification says that the closest Memento should be selected. (Relates to #188 )

**Comment by acoburn** [comment]
Indeed -- in that case, the response should definitely be the first memento.

**Comment by ajs6f** [comment]
Just a note that this just bit me in the butt (the change requires backend changes). It might be good to document this behavior requirement in the Javadocs for `MementoService::get`.
