### ISSUE TITLE
Improve WebAC cache mechanism

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#481]
The WebAC cache mechanism is based on a resourceID - webID - origin tuple, but this will lead to a high number of cache misses, given the variability of the origin portion. It would be possible to vastly improve this if we add a method to the `CacheService` api along the lines of `V getIfPresent(K key)` where null is returned if the entry is not present in the cache.

**Comment by ajs6f** [comment]
Not against this at all, but plain `::get` would align with `java.util.Map` semantics, which might be less surprising than a new method name.

**Comment by acoburn** [comment]
Good point. That method name makes sense to me.

That said, I may be able to accomplish the same thing inside the `CacheService` implementation, which would end up being a lot less disruptive. So I may end up closing this ticket as "won't fix"

**Comment by acoburn** [comment]
It looks like I can accomplish this more easily in a separate layer, so I am going to close this
