### ISSUE TITLE
Change `AuditService` API to use Jena types directly

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#482]
Part of https://github.com/trellis-ldp/trellis/issues/358

I think we can safely change `AuditService` to use Jena types directly (instead of Commons RDF) without changing anything else. It will mean some explicit conversion in classes that (temporarily) use both (e.g. in `-http`) but this seems a not unreasonable price to pay to be able to do the larger migration gradually.

**Comment by acoburn** [comment]
With the upcoming Jena 3.15 release, we will be able to use the Jena-managed Commons RDF implementation directly, which will eliminate all the issues we have with using the commons-rdf-jena module.
