### ISSUE TITLE
User Provided PROV Metadata

### ISSUE THREAD

**Issue by lgleim** [trellis-ldp/trellis#488]
I love that Trellis automatically collects provenance data w.r.t. the creation and modification history of its managed resources. 
However, I currently do not see a "correct" way to store user provided provenance data, such as additional information about the `Used` resources, which other `Entity`s any given entity might have been derived off, that it may be a new revision of another entity with previously different identifier etc. 
Since the code base already[ contains definitions for the entire PROV vocabulary](https://github.com/trellis-ldp/trellis/blob/master/core/vocabulary/src/main/java/org/trellisldp/vocabulary/PROV.java), I was wondering whether you might be interested in accepting a pull request that enables user supplied PROV provenance information. 
I am also currently evaluating what the "correct" way to do this would be, since I am not aware of any standard w.r.t. providing provenance information to an LDP server or even any REST endpoint. As far as that goes, I am only aware of the [PROV-AQ](https://www.w3.org/TR/2013/NOTE-prov-aq-20130430/) standard.

**Comment by lgleim** [comment]
> If you'd like to store user-provided provenance information in your LDP resource, just put those triples in with the rest of the RDF.

Does this also work for Non-RDF Sources though? 
Implementing an extended `AuditService` is exactly what I first had in mind, especially given that `org.trellisldp.api.ResourceService` and `org.trellisldp.api.AuditService` may be implemented independently of each other for the Persistence Layer and thus end up in different storage systems. Given the Memento/TimeGate implementation, my understanding is, that all records are effectively immutable anyway, correct?

**Comment by lgleim** [comment]
First of all thank you very much for the quick and detailed responses! 

> Yes, Non-RDF resources each have an RDF description (follow the rel="describedby" Link header), and you can place arbitrary RDF there.

Again, a few (too many) questions just to make sure I am not getting this wrong:
1. While the [LDP Primer](https://www.w3.org/TR/ldp-primer/#creating-a-non-rdf-binary-resource-post-an-image-to-an-ldp-bc) provides such an (non-normative) example, this is not actually standardized behavior, correct?
2. Supplying this metadata requires at least one additional round trip (create Non-Rdf, get Response with `rel="describedby"` Link header, post metadata to that URI, wait for response)?
3. There will still be a distict immutable audit record (if enabled), independent of the description?
4. The description is by no way enforced to be an RDF Resource (c.f. https://www.w3.org/TR/ldp/#link-relation-describedby)? 

> In a sense, yes, Memento resources are immutable, but there are some distinctions that one can make between the immutability of Mementos and the immutability of audit records: first, mementos have a time resolution of 1 second (as per the specification) and audit records don't have that restriction.

1. If the update rate is higher than 1 record per second (e.g. 1 record/ms), which record would be retrieved by the memento identifier? (probably the one closest to the provided timestamp as required by the standard?)
2. Does the trellis API provide a way to retrieve Mementos at a granularity finer that what the `Accept-Datetime` request header allows (e.g. `Thu, 31 May 2007 20:35:00 GMT`)? Maybe something like `https://example.org/repository/resource?version=1508889600734.012345`? Or are they not actually stored in this case?

> I would add that a Trellis instance can add arbitrary information (in RDF) to the audit/immutable data, including information that never appeared as part of the resource (or in the case of NonRDFs, its description). 

So this should conceptually always happen in the `AuditService`, correct? Or is there also justification to do this in the `ResourceService`?

> That's not at all true of Mementos-- they are supposed to be only what the RDF of that resource (or presumably, its description) was at that time.

This completely makes sense to me. As such it also makes sense to keep Provenance information separate. However:

1. The `Prefer: return=representation; include="http://www.trellisldp.org/ns/trellis#PreferAudit"` Headers are completely custom though and the retrieval process not standardized anywhere, correct? 
2. How do you envision `rel="describedby"`-type metadata and Trellis Audit Records to play together in the best case and does this differ for RDF / Non-RDF Resources?

> The split comes in ResourceService, where some methods deal with immutable and others with mutable information. Hopefully, the details are clear from the Javadocs, and if not, holler!

Thanks so much for the pointer! :)

**Comment by ajs6f** [comment]
Just a few follow-ups:

> The existing implementations store mementos at a 1 second resolution because the sub-second rounding issues turn out to be really confusing to HTTP clients. 

This is not true of `trellis-cassandra`. It stores _all_ Mementos and if asked for a Memento when more than one would satisfy, normally chooses the most recent. That's a bit arbitrary, but I wanted to at least _record_ all the possibly-interesting info.

> So this should conceptually always happen in the AuditService, correct? Or is there also justification to do this in the ResourceService?

@acoburn was relatively mild in his response: I would go further. I think you should _always_ add immutable tuples in the `AuditService`. I think adding them in the `ResourceService` could be very, very confusing over the long haul.
