### ISSUE TITLE
Remove webac support for acl:origin

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#490]
As of #9, the WebAC module supports `acl:origin`; however, this feature is not very clearly defined by the Solid WebAC specification, and it is a bit unclear whether the implementation is correct. More significantly, though, it is questionable whether the security issue that this feature is designed to address is actually addressed with this feature (Origin headers can be spoofed). I would propose reverting this change at least until this feature is more formally defined (if it even makes it into the eventual formalization of the WebAC specification)

**Comment by ajs6f** [comment]
👍
