### ISSUE TITLE
Review JAX-RS injection mechanisms

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#495]
The JAX-RS classes (resource matches and filters) currently make use of constructor injection, which makes unit testing really straight-forward, and this works via CDI injection as expected with both Jersey and CXF. RESTeasy, however, does not support constructor injection, which makes it harder to use the `TrellisHttpResource` class out-of-the-box with Quarkus.

As an alternative, we could change the `TrellisHttpResource` and `AgentAuthorizationFilter` classes to support either field injection or setter injection. (I would opt for setter injection.)

The other services at the Trellis API level can continue to use ctor injection without issue.

**Comment by acoburn** [comment]
I was thinking about this a bit today, and if we move toward either field or setter injection, we could possibly dispense with the `ServiceBundler` construct. The only purpose of that interface was to avoid having constructors with dozens of arguments. It would also become easier to break the `TrellisHttpResource` class into smaller units (which @ajs6f has suggested in the past)

**Comment by ajs6f** [comment]
We can remove `ServiceBundler` by factoring, as you rightly say, so I don't think it makes an argument to introduce a new kind of injection.
