### ISSUE TITLE
Review MementoService methods

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#496]
The MementoService currently has a single method for extracting a list of the available mementos, which is required for generating a `TimeMap` resource. At all other times, however, the memento service really only needs to generate a datastructure that contains the following:

* first memento
* last memento
* previous memento (if the current resource is, itself, a Memento)
* next memento (if the current resource is, itself, a Memento)

For resources with a large number of mementos, it would likely be more efficient to extract only those mementos that are relevant (for non-TimeMap requests), though this method could have a default implementation that extracts these values from the `MementoService::mementos` method.

This new method could accept a nullable `Instant` (to distinguish between the case of the current request being for a Memento and the case where the request is for something else), returning a concrete class with accessor methods for the various values outlined above.

There is also no mechanism for deleting Mementos in the interface. Whether the HTTP layer provides access to such a method or not, I would like to have at least some method at the Java API level to delete Mementos. That method could either go into the API itself or just be a method defined by the implementing class.

**Comment by ajs6f** [comment]
1. Layering behavior makes sense here. I can't do anything with that in `t-c*`, but I'm sure some backends could. 

2. I'm not sure what 
> This new method could accept a nullable Instant (to distinguish between the case of the current request being for a Memento and the case where the request is for something else)

means. If this is a method of `MementoService`, then everything being requested is a Memento, no?

3. I would keep that out of the API unless we have a very clear and present use case for presenting it via HTTP. That could just be an extra `public` method on some backends, a matter of convention.

**Comment by acoburn** [comment]
> > This new method could accept a nullable Instant (to distinguish between the case of the current request being for a Memento and the case where the request is for something else)
> 
> means. If this is a method of `MementoService`, then everything being requested is a Memento, no?

Memento-related link headers are generated for both Memento and non-Memento resources. The difference in this context relates to whether the `rel="next"` and/or `rel="prev"` links are present. If the request is for a Memento, then those (next/prev) links will be present; otherwise, they will not be present.

> I would keep that out of the API unless we have a very clear and present use case for presenting it via HTTP. That could just be an extra public method on some backends, a matter of convention.

Are you referring to the deletion mechanism here?

**Comment by ajs6f** [comment]
I don't understand how that changes the question at the Java layer. What are the exact semantics of the nullable `Instant`, and what would you call it? Maybe that will help me.

Otherwise, yes, I'm sorry for the confusion-- I meant the deletion method.

**Comment by acoburn** [comment]
The `MementoLinks` class would have real accessor methods, but this gives you an idea. This is basically what happens right now inside the HTTP layer, but it would provide an opportunity for an implementation of the MementoService interface to optimize how the data is retrieved, especially if there is a very large number of mementos.


```java
public class MementoLinks {
    public Instant first;
    public Instant last;
    public Instant next;
    public Instant prev;
}

public interface MementoService {

    default CompletionStage<MementoLinks> getMementoLinks(IRI identifier) {
        return getMementoLinks(identifier, null);
    }
    default CompletionStage<MementoLinks> getMementoLinks(IRI identifier, Instant version) {
        return mementos(identifier).thenApply(mementos -> {
            MementoLinks links = new MementoLinks();
            if (!mementos.isEmpty()) {
                links.first = mementos.first();
                links.last = mementos.last();
                if (version != null && mementos.first().isBefore(version)) {
                    links.prev = mementos.headSet(version).last();
                    mementos.tailSet(version).stream().filter(version::isBefore)
                                .findFirst().ifPresent(next -> links.next = next);
                }
            }
            return links;
        });
    }
```

**Comment by ajs6f** [comment]
I'm not sure I understand the code-- neither `SortedSet::headSet` nor `::tailSet` have defined semantics for a `null` input, to me understanding. Let me put it this way: let's say I have three Mementos for a resource, and I call the new `:getMementoLinks(myIRI, null)`. What should be the values of the fields in the returned `MementoLinks`?

**Comment by acoburn** [comment]
for `getMementoLinks(myIRI, null)`, the fields in `MementoLinks` would be:

```
links.first -> the `Instant` of the first memento
links.last -> the `Instant` of the third memento
links.next -> null
links.prev -> null
```

Alternatively, rather than `null`, say the second arg is an instant referring to the first memento:

```
links.first -> the `Instant` of the first memento
links.last -> the `Instant` of the third memento
links.next -> the `Instant` of the second memento
links.prev -> null
```

Or, if the second arg is an instant referring to the second memento:

```
links.first -> the `Instant` of the first memento
links.last -> the `Instant` of the third memento
links.next -> the `Instant` of the third memento
links.prev -> the `Instant` of the first memento
```

Or, if the second arg is an instant referring to the third memento:

```
links.first -> the `Instant` of the first memento
links.last -> the `Instant` of the third memento
links.next -> null
links.prev -> the `Instant` of the second memento
```

**Comment by acoburn** [comment]
Also, w/r/t `SortedSet::headSet`, `::tailSet` and a null value, that won't happen: c.f. the null check.

**Comment by ajs6f** [comment]
Ok, I understand the cases now, thank goodness. But this seems to me more like:
```
public whatever MementoService {
    Instant firstMemento(IRI id);
    Instant lastMemento(IRI id);
    Optional<Instant> nextMemento(IRI id, @NotNull Instant when);
    Optional<Instant> prevMemento(IRI id, @NotNull Instant when);
}
```
I'm adding four methods, but you're adding two methods and a class with four methods, so hm.

**Comment by acoburn** [comment]
The difference between our suggestions has more to do with how a backend may lookup those mementos. In the current code, the process is this: for a given resource IRI, the timestamp for every memento is looked up, sorted and then filtered to produce between two and four headers (first, last, next, prev).

In cases where a resource may have, say, 100,000 mementos, this makes it possible to avoid having to fetch and sort all of those values. Instead, depending on how the backend data is stored/managed, one could structure a request that is considerably more efficient.

For TimeMaps, the full set of mementos will still need to be retrieved, but that's really not necessary for the common case (i.e. a simple GET for the current state of a resource)

**Comment by ajs6f** [comment]
I get the desire to avoid having to sort all the stuff in the front end, but it does in fact have to be sorted, if you want to know what the first and last guys are. You are asking to let the back end do that (and potentially only once if the back end has a sorted layout), which is fine with me.

I don't get why our suggestions are different there. Neither one requires all the stuff to be sorted in the front end (your `default` impl does that, and I'm sure mine would too, but that's the default, not what we hope people would do). We are both "writing queries" to get (say) the previous Memento, but I am returning it directly and you are then packing into a datastructure. (Just realized that I forgot to add asynchrony to my example, but you can see how that would go.)

I'm not gong to make a fuss about this, but it seems to me that you are pushing some calculations from the HTTP layer to the API (in those default methods) and then possibly into the back end (for the right override), which isn't unreasonable at all, but to be blunt, I would be really surprised if this made a lot of real-world difference. Are you seeing numbers that make you think that long lists of Mementos are causing problems?

**Comment by ajs6f** [comment]
Thinking more about this, it feels a bit like premature optimization in the absence of hard evidence that getting a list of Mementos is a pain point. (Maybe that evidence is there and I just haven't seen it yet?) In exchange for an extra short-lived object or three per request (a guaranteed small slowdown) we would be gambling that at least one backend can write a query to get the first/last/prev/next Mementos that is significantly more efficient than getting all of them. For any back end I know, getting all of them looks something like:
```
SELECT memento FROM someMementoTable WHERE resourceId = theIdIWasGiven;
```
and I don't know how that gets a lot more efficient, given that it's a retrieval on what is almost certainly going to be a primary-key-type-thing-for-whatever-that-means-for-that-backend.

Maybe I could understand this better if you could give me an example of a back end that would override here (for any version of the Java) and how it would look (super-roughly) in the sequel?

**Comment by acoburn** [comment]
> Are you seeing numbers that make you think that long lists of Mementos are causing problems?

This is an excellent point. This may very well be a case of premature optimization. At the very least, I do think that we can wait on any changes here until we start seeing actual performance degradation.

**Comment by ajs6f** [comment]
Ok, that's super fair. Are you interested in trying to get this onto @gregjan's plate (i.e. to maybe do a test run or two that build resources with huge numbers of Mementos)?
