### ISSUE TITLE
Implement microprofile-based OAuth module

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#508]
The current OAuth module makes use of `jjwt` for JWT token parsing. For microprofile-based deployments, a [MP-JWT](https://www.eclipse.org/community/eclipse_newsletter/2017/september/article2.php)-based module would make more sense. Plus, there will likely be very little implementation code for us to write.

**Comment by ajs6f** [comment]
I didn't know that MP offered that, but it sure makes sense to reuse if possible. 👍
