### ISSUE TITLE
Where are build logs?

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#509]
For this Gradle novice, where are build logs from tests to be found? I can only find test reports that describe test and test client operation, but not logs from the container that is actually running Trellis (or from unit tests). Specifically, this question relates to `trellis-http` and its Jersey-framework-supported tests, if that makes a difference, which I suspect it might.

**Comment by acoburn** [comment]
When I want to see additional output, I add a flag to the `./gradle` command, such as `--info` or `--debug`.

**Comment by ajs6f** [comment]
Thanks, but that's not quite what I mean. That just shows more logging from the test code. I'm trying to get to the logging from the application itself. Normally I would expect that to be coming through an SLF4J impl, but in a module like `trellis-http`, I can't tell (because Gradle) what the dependencies are. Can (for example) inject a log4j config via system property and capture the logging that way?

**Comment by acoburn** [comment]
Each of the trellis modules depends only on slf4j. The logback dependencies are only for tests, so an application that uses `trellis-http` should be free to use whatever logging system it chooses. The dropwizard-based apps have their own way of handling [log config](https://github.com/trellis-ldp/trellis/blob/master/platform/server/src/dist/etc/config.yml#L14-L25), though I don't suspect that you are asking about the Dropwizard apps. So yes, in principle, you could use add log4j or any other logging system.

**Comment by ajs6f** [comment]
> The logback dependencies are only for tests

Aha! That's what I needed to know. The SLF4J impl for tests is logback. Thanks!
