### ISSUE TITLE
Consider removing AgentService

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#512]
The `AgentService` interface does one thing: it converts the String from `java.security.Principal::getName` into an IRI. As it is, the entire code, effectively, consists of calling `RDF::createIRI`.

The advantage of the indirection is that one could, conceivably, inject a custom `AgentService` that performs an additional lookup or which follows certain business logic. (In practice, there appear to be no use cases for this level of indirection)

The counter-argument is that that sort of mapping should occur in the Authentication layer; having it elsewhere in the code base is confusing. As it is, we could easily place all the `AgentService` features directly in the HTTP (and WebDAV) layers. At the same time, the `trellis-agent` module could be dropped and other interfaces simplified.

I am inclined to remove the `AgentService` interface, but what do others think?

**Comment by ajs6f** [comment]
I have no use cases in hand, so 💣 away.

**Comment by acoburn** [comment]
In working on this, it appears that I can also remove the `o.t.http.AgentAuthenticationFilter` class and simplify a lot of the session management
