### ISSUE TITLE
Add session information to mutating ResourceService methods

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#56]
The mutating ResourceService methods (`::create`, `::replace` and `::delete`) will cause events to be emitted. Before the recent refactor in #31, this data had been available in the Audit-related triples, but now that data is only included in the `::add` method. By including a `Session` value (or similar) in the mutating methods, it would be possible to get access to these data.

This would also be an opportunity to remove the use of the default graph in these methods, the purpose of which relates only to providing data to the event producer. This likely will require adding a field (e.g. `baseURL`) to the `Session` type. This will also lead to some cleaner code in the HTTP layer.

**Comment by ajs6f** [comment]
Is that `baseURL` just to be able to put URLs into event serializations?

**Comment by acoburn** [comment]
Yes, that is the only purpose of `baseURL`. You can see how this works at present: https://github.com/trellis-ldp/trellis/blob/master/trellis-triplestore/src/main/java/org/trellisldp/triplestore/TriplestoreResourceService.java#L235-L241 (it's rather awkward)

**Comment by ajs6f** [comment]
That's cool. I just wouldn't (and I bet you don't) want to see any logic based on that value, not down into the below-HTTP layer.

**Comment by acoburn** [comment]
Exactly. And by making that value a simple field of a `Session` type, there would be no need to sift through the `Dataset` that is passed into the persistence layer.

**Comment by ajs6f** [comment]
You know I'm all over that like brown on rice!
