### ISSUE TITLE
Problems with Memento tests

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#563]
We've been having difficulty with flaky Memento tests for a long time.  Recently, I've been blocked on  https://github.com/trellis-ldp/trellis-cassandra/issues/62 because of the following failures:
```
[ERROR]   MementoBinaryIT.testMementoContent Check the number of distinct Memento responses ==> expected: <2> but was: <1>
[ERROR]   MementoBinaryIT.testMementoDateTimeHeader Check that the memento-datetime header is correct ==> expected: <2019-10-23T21:16:36Z> but was: <2019-10-23T21:16:40Z>
[ERROR]   MementoResourceIT.testMementoDateTimeHeader Check that the memento-datetime header is correct ==> expected: <2019-10-23T21:16:48Z> but was: <2019-10-23T21:16:52Z>
[ERROR]   MementoTimeGateIT.testTimeGateRequestPrecedingMemento Check for a valid response ==> expected: <SUCCESSFUL> but was: <CLIENT_ERROR>
```

and after discussion with @acoburn, it seems like the best approach is to rebuild these tests in a more reliable form.

**Comment by acoburn** [comment]
I think this issue has more to do with a slight difference in the memento implementation in trellis-cassandra, but it still warrants further investigation.

**Comment by acoburn** [comment]
It seems that this issue still needs some work.
