### ISSUE TITLE
HTTP/2 over TLS  support requires ALPN dependency

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis#58]
In order to make trellis-app with dropwizard's h2 support configuration in JDK 9 or JDK 10, I added a dependency:
```groovy
compile group: 'org.eclipse.jetty', name: 'jetty-alpn-java-server', version: '9.4.8.v20171121'
```
This version is built for JDK 9, but it works on JDK 10.

**Comment by acoburn** [comment]
@christopher-johnson would make sense to add a profile that selectively adds this dependency? I would want to make sure that h2 is still well supported on JDK 1.8

**Comment by christopher-johnson** [comment]
In order to make ALPN work on JDK 8, one needs to add `-Xbootclasspath/p:$path_to_alpn_boot.jar` as a JVM option.  This is probably not feasible to do with gradle as it involves copying the alpn_boot library (from some flat_dir in the repo) to the build host, and then adding a `applicationDefaultJvmArgs` to modify the application start script.  It is pretty easy to set `JAVA_OPTS` in docker, and then copy the lib into the image at that path, with something like this:
```yaml
ENV ALPN_BOOT alpn-boot-8.1.12.v20180117.jar
ENV TRELLIS_RUNTIME /opt
ENV JAVA_OPTS="-Xms250m -Xmx1024m -Xbootclasspath/p:${TRELLIS_RUNTIME}/${ALPN_BOOT}"
```
I tested this and it works.

The question of how or if to conditionally support 9 ,10 and eventually 11 builds in the trellis gradle scripts is open.  To build trellis-app with H2 for 9 only requires a couple of changes (adding the compile dependency on alpn-java-server and changing the target to 1.9).   The alpn-java-server is a transitive dependency that is already included with dropwizard http2, and I guess the gradle declaration includes it to the runtime classpath(?).

To build for 10 requires excluding jacoco (you know about this), and to avoid javadoc warnings, adding this:
```groovy
task docs(type: Javadoc) {
        doFirst {
            if (Jvm.current().getJavaVersion().isJava10Compatible()) {
                addBooleanOption('html5', true)
            }
        }
    ...
```   
One other note is that the trellis-app `build.gradle` includes this:
```groovy
artifacts {
    archives javadocJar
    archives sourceJar
}
```
I think that this can be removed since it is already in the rootProject build.gradle.

**Comment by acoburn** [comment]
@christopher-johnson feel free to issue a PR that removes the redundant `artifacts` section.

For the ALPN support in JDK 1.8, it seems like a docker-based solution would be best.

As for supporting jdk9+ builds, this will probably be an ongoing discussion. I'd like to have really solid support for JDK 1.8 but at the same time make it possible to build for newer environments. If that involves profiles or gradle conditional logic, let's continue to explore that.

**Comment by acoburn** [comment]
This issue seems to be very much dependent on the deployment environment with little, if anything, to do with the Trellis codebase. I would like to either suggest that this issue be closed as-is (with no changes) or else be closed after some relevant documentation is added to one of the README files.
