### ISSUE TITLE
Resource Subscriptions with Trellis Notifications

### ISSUE THREAD

**Issue by Aliam51** [trellis-ldp/trellis#593]
I have a few questions about notifications in Trellis.
My goal is to enable external applications to subscribe to change notifications concerning specific resources in Trellis.
Do you have any recommendations how that can be achieved with Trellis notifications? 

I tried to setup subscriptions on resource level with JMS and ActiveMQ. 
Unfortunately, Trellis publishes all messages to the same topic or queue and the object id is not exposed in the message header, so JMS Message Selectors can’t be used to subscribe to specific resources. 

I also looked at WebSub as a possible solution. Is there any documentation on how to setup Trellis to publish to a WebSub hub? As I understand it, the hubUrl parameter in the config.yml only enables the HTTP header.

I think a Notifications section in the “[App Configuration Guide](https://github.com/trellis-ldp/trellis/wiki/App-Configuration-Guide)” in the Wiki would be helpful. 
Side note: The dropwizard.io links in the “App Configuration Guide” seem to be broken.

**Comment by acoburn** [comment]
As you have discovered, Trellis provides only a single notification stream. That said, it is entirely possible to implement a per-resource notification stream on top of that structure. If you are familiar with [Apache Camel](https://camel.apache.org), I can point you to some [specific](https://github.com/trellis-ldp/camel-ldp-recipes/blob/master/websub/src/main/java/org/trellisldp/ext/websub/WebSubRouter.java#L36-L47) [examples](https://www.dropwizard.io/en/stable/manual/configuration.html). In particular, the `ActivityStreamProcessor` from the [camel-ldp project](https://github.com/trellis-ldp/camel-ldp) will transform the JSON-LD notification data into JMS headers, which would allow you to use a variety of existing JMS-based selectors to filter the notification stream. That said, any message-oriented middleware can be used for this.

WebSub would be a possible solution, but Trellis only provides one part of that. The WebSub Hub would need to be an independent piece of software. There is an existing camel-based project that connects the Trellis event stream to an external WebSubHub: https://github.com/trellis-ldp/camel-ldp-recipes/tree/master/websub, but there isn't any documentation on setting that up. In any case, you are correct: on the Trellis side, the `hubUrl` configuration only results in generating the HTTP header.

Yes, a notifications section would be great along with some examples of the sorts of application-specific features one could build on top of the server-wide event stream. BTW, I have fixed the dropwizard links.

**Comment by Aliam51** [comment]
Thank you very much for your fast and helpful response!
The `ActivityStreamProcessor` looks promising.
Unfortunately, I’m not familiar with Apache Camel (yet). 
How can I set up the integration with Trellis? 
Or more specifically, how do I get the ActivityStream from Trellis into the Processor?

**Comment by acoburn** [comment]
Effectively, you will want to use some sort of middleware for this. Camel is only one example, though for Java-based environments, it is one of the more mature open source systems in this space (and I would recommend it). In terms of creating an integration, there are several examples for creating "camel routes" in the [camel-ldp-recipes](https://github.com/trellis-ldp/camel-ldp-recipes). Similarly, there are plenty of options for deploying these integrations once they have been developed. Referring to the [camel website](https://camel.apache.org) would be your best bet, especially their [getting started guide](https://camel.apache.org/manual/latest/getting-started.html)

**Comment by Aliam51** [comment]
I got it working. 
Thanks!
