### ISSUE TITLE
`MutableDataService::create` vs `::replace`

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#62]
If `::replace` is called with an identifier for a resource that does not already exist, should `::replace` return without trying to mutate anything (and presumably with a `false`-valued `Future`)?

I think so, but wanted to make sure.

**Comment by ajs6f** [comment]
Similarly, if `::create` is called for an identifier that exists, should it not return without persisting anything (and with a false-valued Future)?

**Comment by ajs6f** [comment]
If so, I will add those semantics to the Javadocs.

**Comment by ajs6f** [comment]
To be clear, the reason I'm suddenly concerned about this is because conditional writes (or just reading before writing) are terribly unidiomatic for Cassandra. So I really want to be told I'm wrong here, and that these methods _don't_ have to check beforehand before writing. But we have to get the story straight.

**Comment by acoburn** [comment]
From the perspective of the target resource, `::create` and `::replace` both could act as a `PUT` operation (that's how it works in both the triplestore and the kafka implementations, though a backend focused on consistency could wrap everything in transactions).

Given that, you could conceivably get multiple concurrent `::create` operations for the same resource; that is, a `::create` for a resource that already exists. Similarly, one could imagine an interleaving of `::replace` and `::delete` operations such that `::replace` is called on a non-existent resource. To a certain degree, the behavior is really up to the implementation. If I were writing a Cassandra implementation, I'd just make `::create` and `::replace` both act like `::put` w/r/t Cassandra rows.

Where the semantics of the two methods differ relates to what happens to _other_ resources. For example, `::create` should cause the last modified date of the parent container to be updated while `::replace` wouldn't (likewise with the updating of `ldp:contains` triples).

What I would say is that `::replace` operations do not need to check the persistence layer -- in fact, the trellis-http layer has already checked for the existence of a resource in that location, so there certainly is no need to re-check its existence.

Another question that this issue raises is this: what is the meaning of a response of `Future<false>`? At present, that triggers a 500 HTTP error. But maybe that should be reserved for a thrown runtime exception? and a `Future<false>` should result in a 4xx error?

**Comment by acoburn** [comment]
Yes, please open another issue to discuss the meaning of `Future<false>` and the appropriate HTTP response.

**Comment by acoburn** [comment]
@ajs6f is this issue still relevant or should it be closed?

**Comment by ajs6f** [comment]
No, the resolution is here in your comment:

> ::replace operations do not need to check the persistence layer -- in fact, the trellis-http layer has already checked for the existence of a resource in that location, so there certainly is no need to re-check its existence.
