### ISSUE TITLE
Restructure tests

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#71]
The `trellis-test` module contains a number of test suites that can be used by applications. The current pattern is to subclass the various types, but it would be a cleaner pattern to make use of JUnit5 interfaces with default methods as described here: https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-interfaces-and-default-methods

**Comment by ajs6f** [comment]
It would be ideal as well to factor apart those tests that can run directly against a backend from those that require a full app to be built up.
