### ISSUE TITLE
Funky javadoc 

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#77]
`org.trellisldp.api.ResourceService.getMementos(IRI)` currently has Javadoc:
```
    /**
     * Retrieve a list of Mementos for this resource.
     *
     * @param identifier the resource identifier
     * @return a stream of known Mementos
     */
    List<Range<Instant>> getMementos(IRI identifier);
```

which I _think_ dates to before the introduction of ranges for Mementos. I'd send a PR to correct it, but I'm honestly not sure what the semantics of the return value _are_. Is it a `List` of `Ranges` of `Instant`s for which any `Instant` that is within a given `Range` has a Memento associated to that `Range`?

**Comment by acoburn** [comment]
The javadocs are just wrong. The return type is a `List` of `Range`s of `Instant`s. Each element of the list can be used to build a link header for a single Memento (i.e. for the `from` and `until` parameters).

**Comment by acoburn** [comment]
Resolved via https://github.com/trellis-ldp/trellis/commit/344337420b5b23434c6648842f7beda41b8a4b4a
