### ISSUE TITLE
Peculiar test failure

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#86]
I have switched to using the recently refactored `trellis-test` tests, and everything still passes, except for one oddity: `Fetch the JSON-LD serialization with a custom profile(RDF Serialization tests)` fails with a 
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.LinkedHashMap` out of START_ARRAY token
 at [Source: (String)"[{"@id":"http://localhost:52634/1bab8cce-0def-46ef-9a55-64bb72ddb2ee/2a9e3389-2067-4b23-9226-d3bd9a555720","http://www.w3.org/ns/oa#hasTarget":[{"@id":"http://example.org/page1"}],"http://www.w3.org/ns/oa#hasBody":[{"@id":"http://example.org/post1"}],"@type":["http://www.w3.org/ns/oa#Annotation"]}]
"; line: 1, column: 1]
```

I've got the full trace [here](https://gist.github.com/ajs6f/10e28fa8548eed1c82c8c4ebaaf9e587). Anything obvious? I'm really surprised to see serialization errors appear. Maybe a problem with dependencies?

**Comment by acoburn** [comment]
That test is assuming that your application container supports fetching remote `@context` (profile) documents. You can either enable that sort of thing in your [app config](https://github.com/trellis-ldp/trellis/blob/master/trellis-app/src/test/resources/trellis-config.yml#L54-L55), or you can disable the test entirely by overriding the `supportWebAnnotationProfile` method (i.e. return `false`) as here: https://github.com/trellis-ldp/trellis/blob/master/trellis-test/src/main/java/org/trellisldp/test/AbstractApplicationLdpTests.java#L47-L49

I wanted to make that configurable, but if there's a better way to do that -- maybe making the default to skip the test would be better?

**Comment by ajs6f** [comment]
Thanks, that got me going again. Well, my choice would actually be to factor out those tests that rely on that function into a separate class. I'd rather aggregate the tests I _want_ than make choices to turn off those I don't.

**Comment by acoburn** [comment]
Factoring it out into its own class would be easy to do.

**Comment by ajs6f** [comment]
New ticket?

**Comment by acoburn** [comment]
Sure, if you'd like, or you can re-open #71, which is a pretty generic catch-all for this.

**Comment by ajs6f** [comment]
I'll be specific.
