### ISSUE TITLE
Who creates containment triples?

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#91]
Having enabled the new `ResourceServiceTests` I'm getting a failure at https://github.com/trellis-ldp/trellis/blob/651bd25595cb2bccee42a1f82e7b9845712c9e65/trellis-test/src/main/java/org/trellisldp/test/ResourceServiceTests.java#L410
of the form `expected: <2> but was: <0>`. Presumably this is because I am not producing the containment triples from the backend (which my backend is not, in fact, doing). But I was under the impression that it is `trellis-http` that is responsible for creating the containment triples and passing them into the backend. WRT quads, my backend just serializes what it is given and deserializes it (with the exceptional case of an LDP-NR, when it parses the quads to get some metadata).

Am I missing something? How can the `ResourceServiceTests` expect to find containment triples in the absence of `trellis-http`?

**Comment by acoburn** [comment]
The HTTP layer does not generate the containment quads. There are several reasons for this related to both concurrency and scale. In the triplestore impl, I store a child -> parent link on each resource (rather than the LDP parent -> child triple), and then dynamically generate the containment triples by running a query that reverses that relationship. If it would be helpful, we could certainly have the HTTP layer add this child -> parent link. But having the http layer keep track of all of a resource's children would be rather problematic.

**Comment by ajs6f** [comment]
Ok, I see that. But then how does the backend know how to produce those links? The backend may have no idea what a resource's container is. And supposing it does know, is it responsible for adding (or removing) membership triples to the parent?

**Comment by acoburn** [comment]
That's the role of the `ResourceService::getContainer` method. A backend can override the default impl if it has a different way to keep track of containment.

**Comment by ajs6f** [comment]
I can see that `ResourceService::getContainer` does fine to _return_ the containment info out of the backend. But how does it get there to begin with?

**Comment by acoburn** [comment]
One of the distinct advantages to having you independently implement a persistence layer is that you bring to the fore all of my built-in assumptions about the inner working of this code. This is another such case where the persistence layer is simply assuming that containment works in a particular way. As it is, there is nothing -- _absolutely nothing_ -- in the code to inform a newly created child resource of the existence of its parent. I suspect that the best way to address this would be to have the HTTP layer explicitly add that `trellis:PreferServerManaged <child> dc:isPartOf <parent> .` quad to the dataset that is passed along to `::create`, `::delete` and `::replace`.

**Comment by ajs6f** [comment]
Hey, that's why I'm your back-seat driver, right!

I'm going to come right back at you about how to do this, tho'. Rather than put stuff in the quads (and thence forcing every backend impl to write the same RDF munging code) can we break it out as a param?

If we make the "resources can be contained by at most one container" assumption, we just need an additional `final IRI container` param.

Admittedly, we're starting to pile up a bunch of params in those methods, so we might want to factor that around, but since those are very very hot methods (any mutating request goes through at least one of the three mutable-data methods and also `::add`) I don't feel too bad about that yet.

**Comment by acoburn** [comment]
Adding a parameter to those methods seems like a good idea.
