### ISSUE TITLE
Add a method on ResourceService listing the supported interaction models

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#92]
As discussed in #88, it would be helpful to introduce a method on the `ResourceService` interface that returns the supported LDP interaction models. That way, failures for non-supported LDP types can happen higher in the stack. It also makes testing more flexible, as non-relevant tests can be ignored.

One possibility for the signature for this method could be:

```java
Set<IRI> ResourceService::supportedInteractionModels();
```
 
The default implementation could include all LDP resource types (LDP-RS, LDP-NR, LDP-C, LDP-BC, LDP-DC, LDP-IC) but if a persistence layer has a different level of support, the method can be overridden to list only those types that are supported.

**Comment by ajs6f** [comment]
I would let the default impl return an empty set. Then impl'ers will have to consciously choose what to support, which is a good thing about which to be conscious.
