### ISSUE TITLE
JUnitPlatform causes ClassCastException in Gradle testCompile with JPMS

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis#96]
You may recall that I pointed out [here](https://github.com/trellis-ldp/trellis/pull/79#issuecomment-375083562) about removing the `@RunWith(JUnitPlatform.class)` annotation from the tests.  In doing an analysis of the `ClassCastException` that resulted from running any tests in the JPMS build, I discovered that this problem had nothing to do with the Logger or Gradle, but was actually caused by JUnit4.  

Check out this [passing build](https://travis-ci.org/trellis-ldp/trellis/builds/363478359) and [this commit](https://github.com/trellis-ldp/trellis/commit/797a71abaacc10bdf35589ed3495cccb58100f16) for how to fix this.  I think that it is safe to remove the annotation and the dependencies on the `junit-platform-runner`, but perhaps you want to verify.  Also, there are a few references [like this one](https://github.com/trellis-ldp/trellis/compare/jpms?expand=1#diff-b8a593b35e8912b2df16329cfaa35196) to JUnit4 methods that can be replaced

If you approve, then let me know if you need a PR.  The good thing is that all of the tests are now runnable in the JPMS branch!  I will continue to periodically merge master to keep this in sync.

**Comment by acoburn** [comment]
We definitely want to remove any JUnit4 references. That would be great if you can send a PR. Thanks!

**Comment by christopher-johnson** [comment]
OK.  I just merged master and made the build pass.  A remaining thing is that the PaxExam test depends on JUnit4.  The solution for that is to make the PaxExam.class work with `@ExtendWith` which is the JUnit5 replacement for `@RunWith`.  Is there a JUnit5 driver in the works for PaxExam yet?

**Comment by christopher-johnson** [comment]
I have unfortunately discovered that this exception persists if the `useJUnitPlatform` support is enabled.  Gradle spends a year preparing support for JUnit5, but does not test it in the JPMS?  How is it possible?  See the [epic](https://github.com/gradle/gradle/issues/828)

**Comment by christopher-johnson** [comment]
the good news is that the deprecated `org.junit.platform.gradle.plugin` does not cause the ClassCastExceptions.  I guess that the `useJUnitPlatform` support includes pieces of the `vintage runner`...

**Comment by christopher-johnson** [comment]
Check [here](https://travis-ci.org/trellis-ldp/trellis/builds/363637186) for the latest JPMS build with gradle tests output.  Travis runs the tests and it passes.   A couple of issues with the build.gradle remain.  `install` is now failing for some reason, so I had to disable the `maven` plugin.  May be related to this:
https://jira.spring.io/browse/SPR-13013

The `java` plugin needs to be applied before `javadoc`.  All of the tests are run with the exception of 5 in the `HttpBasedBinaryServiceTest`, two in `AbstractVocabularyTest` and the `OSGiTest`.  Also, the jacocoRootReport cannot be generated because of the explicit build sequence ...

One other note is that anything that depends on` tamaya` also requires `javax.annotation.Priority`.  This needs to be added to dependencies.

**Comment by christopher-johnson** [comment]
The `jacocoRootReport` now works for the JPMS branch.  

I basically mimed the [JUnit5 build.gradle](https://github.com/junit-team/junit5/blob/master/build.gradle) approach, which required a bit of reorganization of your root [build.gradle](https://github.com/christopher-johnson/trellis/blob/jpms/build.gradle).  They are also using [codecov.io](https://codecov.io/gh) that I tested with Travis `after_success:`.  Check the [coverage report here](https://codecov.io/gh/christopher-johnson/trellis/tree/a24ffede6eebeeb3e084218384e5f1e7651e8b6a):  Looks like a nice service ...
