### ISSUE TITLE
CrossOriginResourceSharingFilter is not active

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis#98]
In testing a JS client on trellis-app, I noticed that the CORS headers are not available.  I made an application test and modeled it after the Memento Test design, and I used the configuration `trellis-config.yml`.  Here is a screenshot that shows the contents of the header map.
![screenshot at 2018-04-07 20-44-49](https://user-images.githubusercontent.com/5990301/38459001-910b1c9c-3aa4-11e8-82d9-8ed7be545777.png)

I thought that it could related to the `@PreMatching` filter (similar to https://github.com/trellis-ldp/trellis/issues/49), but removing that has not solved the question.

**Comment by acoburn** [comment]
Make sure your configuration has at least

```yaml
cors:
    enabled: true
```

I just tried this with a recent build from master using this configuration:

```yaml
cors:
    enabled: true
    allowOrigin:
        - "*"
    maxAge: 180
```

With this (simple) request:

```bash
curl -i http://localhost:8080 -H"Origin: http://localhost:8080"
```

The response contains these headers:

```http
Access-Control-Expose-Headers: memento-datetime,preference-applied,accept-patch,accept-post,vary,link,digest,content-type,location,etag,accept-ranges
Access-Control-Allow-Origin: http://localhost:8080
Access-Control-Allow-Credentials: true
```

A pre-flighted non-simple request:

```bash
curl -i -XOPTIONS  http://localhost:8080 -H"Origin: http://localhost:8080" -H"Access-Control-Request-Method: PUT"
```

Returns with these CORS headers:

```http
Access-Control-Allow-Origin: http://localhost:8080
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: DELETE,OPTIONS,PUT,PATCH
Access-Control-Max-Age: 180
```

**Comment by christopher-johnson** [comment]
OK, I see that the client has to provide the Origin Header to get the CORS
response.  This makes sense, though I have never noticed a pre-flight
request that did it that way.  Thanks for the insight!
